content/solutions/altinn-studio-repos/structure/_index.md
content/solutions/altinn-studio-repos/structure/altinnservice-projectfile/_index.md

Added project file to the repository structure and added description for the same
Removed the editions folder from structure

Repository structure update

---

content/development/_index.md
content/development/handbook/_index.md
content/development/handbook/back-end/_index.md
content/development/handbook/front-end/_index.md
content/development/handbook/front-end/error-handling/_index.md
content/development/handbook/front-end/react/_index.md
content/development/handbook/front-end/redux/_index.md
content/development/handbook/front-end/unit-testing/_index.md
content/development/handbook/general/_index.md
content/development/handbook/git/_index.md
content/development/handbook/naming/_index.md

* Added basic development handbook structure, based on altinnpedia
* Added details on front-end error handling to dev handbook

Error handling

---

content/development/handbook/deployment/_index.md
content/development/handbook/front-end/redux/_index.md
content/development/handbook/getting-started/_index.md
content/development/handbook/git/_index.md
content/development/handbook/naming/_index.md
content/development/handbook/test/_index.md
content/development/handbook/test/test-strategy/_index.md
content/development/handbook/test/testcafe/_index.md
content/development/handbook/test/unit-testing/_index.md
content/development/handbook/test/xunit-testing/_index.md
content/technology/jest/_index.md

https://github.com/Altinn/altinn-studio/issues/1041

moved existing documentation into docs.altinn.studio

---

content/development/flight-rules/_index.md

Fix layout so bullet points are shown

fix layout

---

content/getting-started/service-creation/logic/_index.md

Added documentation for validation (both general server-side and single-field). 
Covers documentation for https://github.com/Altinn/altinn-studio/issues/749 and https://github.com/Altinn/altinn-studio/issues/750

750 validations

---

layouts/partials/header.html

Unless I've overlooked and/or misunderstood something, this should fix #27

Added missing '/' to make tags work

---

content/known-issues/_index.md

This needs to be approved before this update:
https://github.com/Altinn/altinn-studio/pull/1120

known issues linked to altinn.studio repo

---

content/development/handbook/front-end/styling/_index.md

[Easy to read version](https://github.com/Altinn/altinn-studio-docs/blob/291e9fc9419c05ed310eb3f427afd5be452e6b16/content/development/handbook/front-end/styling/_index.md)

First version of Styling document.

---

content/development/flight-rules/_index.md

Updated with
- info about runtime.js
- unable to mount error on pod
- how to deploy to production

Updated flight rules

---

content/architecture/application/altinn-studio/_index.md
content/solutions/altinn-studio/altinn-studio-repos/structure/_index.md

1) Updated folder structure in repository structure 
2) Added testing in  altinn studio description

Updated folder structure 

---

content/teknologi/altinnstudio/solutions/altinn-studio/functional/build-app/ui-designer/components/index.md

Resolving https://github.com/Altinn/altinn-studio/issues/3130 and https://github.com/Altinn/altinn-studio/issues/1921 by adding relevant documentation.

Resolve Altinn Studio bugs 3130 + 1921

---

content/teknologi/altinnstudio/development/handbook/test/wcag/_index.md

Some images weren't rendering properly. This should fix it.

fix for image rendering

---

content/teknologi/altinnstudio/altinn-api/_index.md
static/swagger/altinn-platform-storage-v1.json

Related to https://github.com/Altinn/altinn-studio/issues/5105.

Added the excludeConfirmedBy parameter to instance query

---

content/teknologi/altinnstudio/altinn-api/swagger/events/_index.md
static/swagger/altinn-platform-events-v1.json

Related to https://github.com/Altinn/altinn-studio/issues/1783.

Adding swagger file for Platform.Events

---

content/teknologi/altinnstudio/altinn-api/app-api/data-elements/_index.md

Improvements to the documentation of expected Content-Type when uploading a data blob.
Related to https://github.com/Altinn/altinn-studio/issues/5853

Upload data request Content-Type rules.

---

content/teknologi/altinnstudio/changelog/storage-interfaces/v2/whats-new.md

Related to altinn-studio issue: https://github.com/Altinn/altinn-studio/issues/5317

Updated change log for storage interface

---

content/teknologi/altinnstudio/changelog/storage-interfaces/v3/whats-new.md
content/teknologi/altinnstudio/development/handbook/back-end/nuget-package/_index.md

Some minor updates to the procedure of updating nuget packages as well.

Documented the changes in version 3.0.1 of the Storage.Interface nuget.

---

content/teknologi/altinnstudio/changelog/app-nuget/v4/whats-new.md

Changelog entry for 4.1.0 app nuget, related to https://github.com/Altinn/altinn-studio/issues/5754

add changelog entry for v4.1.0

---

content/teknologi/altinnstudio/changelog/app-nuget/v4/whats-new.md

Related to old issue:
https://github.com/Altinn/altinn-studio/issues/5853

Updated ChangeLog for Altinn.App.*. Added entry about 4.0.3.

---

content/teknologi/altinnstudio/changelog/app-frontend/v3/whats-new.md

update app frontend changelog related to https://github.com/Altinn/altinn-studio/issues/6233
Also added missing entries after 3.5.0.

what's new 3.6.0-3.6.2

---

content/teknologi/altinnstudio/changelog/app-frontend/v3/whats-new.md

added missing entries for frontend versions

updated missing entries

---

content/teknologi/altinnstudio/changelog/app-frontend/v3/whats-new.md

Related to issue: https://github.com/Altinn/altinn-studio/issues/6400

Added description of release 3.6.14

---

content/teknologi/altinnstudio/changelog/app-frontend/v3/whats-new.md

Related to https://github.com/Altinn/altinn-studio/issues/5747 and https://github.com/Altinn/altinn-studio/issues/5747

Added most recent frontend updates to changelog

---

content/community/changelog/app-nuget/v4/whats-new/_index.en.md
content/community/contributing/handbook/back-end/nuget-package/_index.md

Updates related to altinn-studio issue:
https://github.com/Altinn/altinn-studio/issues/6707

New versions of Altinn.App packages

---

content/community/changelog/app-frontend/v3/whats-new/_index.en.md
content/community/changelog/app-frontend/v3/whats-new/_index.nb.md

versions 3.11.2 and 3.11.3 and translated versions of nb.

updated app frontend changelog

---

content/community/changelog/app-frontend/v3/whats-new/_index.en.md
content/community/changelog/app-frontend/v3/whats-new/_index.nb.md

[#6775](https://github.com/Altinn/altinn-studio/issues/6775)

changelog for 6775

---

content/community/about/_index.en.md
content/community/about/_index.nb.md
content/community/about/slide.en.md
content/community/about/slide.nb.md
content/community/presentations/_index.en.md
content/community/presentations/_index.nb.md

Presentations cleanup

---

content/community/about/goals/_index.en.md
content/community/about/goals/_index.nb.md
content/community/about/open-source/_index.en.md

Altinn as open source

---

content/community/changelog/app-frontend/v3/whats-new/_index.en.md
content/community/changelog/app-frontend/v3/whats-new/_index.nb.md

[6893](https://github.com/Altinn/altinn-studio/issues/6893)

changelog for 6873 and 6893

---

content/community/changelog/app-frontend/v3/whats-new/_index.en.md
content/community/changelog/app-frontend/v3/whats-new/_index.nb.md

change log for patched deps and [6253](https://github.com/Altinn/altinn-studio/issues/6253)

change log for app frontend

---

content/app/design/usertest/_index.nb.md

rettet på feil i lenke

---

content/api/apps/instances/_index.en.md
content/api/apps/instances/_index.nb.md
content/community/changelog/app-nuget/v4/whats-new/_index.en.md
content/community/changelog/app-nuget/v4/whats-new/_index.nb.md

Note date of nugets should be checked once issue passes test

added doc on new endpoint

---

content/community/changelog/storage-interfaces/v3/_index.en.md
content/community/changelog/storage-interfaces/v3/_index.nb.md

Related to issue: https://github.com/Altinn/altinn-studio/issues/6861

Updated change log for Storage Interfaces

---

.vscode/extensions.json
.vscode/launch.json
.vscode/tasks.json

Better-vscode-integration

---

layouts/partials/topbar.html

Language support for header links

---

content/app/development/configuration/authorisation/_index.en.md
content/app/development/configuration/authorisation/_index.nb.md

Rolle liste

---

content/app/development/ux/fields/grouping/alternatives/_index.en.md
content/app/development/ux/fields/grouping/alternatives/_index.nb.md
content/app/development/ux/fields/grouping/setup/_index.en.md
content/app/development/ux/fields/grouping/setup/_index.nb.md

https://github.com/Altinn/altinn-studio/issues/7164

added info about new params for groups

---

content/community/contributing/handbook/test/cypress/_index.md

solves Altinn/altinn-studio#6944

docs for cypress tests

---

content/community/changelog/app-frontend/v3/whats-new/_index.en.md
content/community/changelog/app-frontend/v3/whats-new/_index.nb.md

changelog for app frontend version 3.22.3

---

content/app/testing/local/_index.en.md
content/app/testing/local/_index.nb.md

page not found fix

---

content/community/contributing/propose-component/_index.en.md
content/community/contributing/propose-component/_index.nb.md

Updated PO in feature-request links

Fixed feature-request links

---

content/app/development/ux/images/_index.en.md
content/app/development/ux/images/_index.nb.md

https://github.com/Altinn/altinn-studio/pull/8132

Pdf docs image

---

content/community/devops/teams/platform/_index.en.md
content/community/devops/teams/platform/_index.nb.md

Initial description of team Platform responsibilities

Team platform responsibilities

---

content/app/app-dev-course/bolk1/_index.nb.md

Lenken til "opprette app" dokumentasjonen var feil

Rettet lenke

---

content/community/changelog/storage-interfaces/v3/_index.en.md
content/community/changelog/storage-interfaces/v3/_index.nb.md
static/swagger/altinn-platform-storage-v1.json

added changelog for storage.interface 3.8.0

---

content/community/changelog/app-nuget/v4/whats-new/_index.en.md
content/community/changelog/app-nuget/v4/whats-new/_index.nb.md

nuget updates

---

content/community/changelog/app-frontend/v3/whats-new/_index.en.md
content/community/changelog/app-frontend/v3/whats-new/_index.nb.md

Updated changelog for feature https://github.com/Altinn/altinn-studio/pull/8238

feat: add information about row/column layout for radio and checkboxes

---

content/community/changelog/app-frontend/v3/whats-new/_index.en.md
content/community/changelog/app-frontend/v3/whats-new/_index.nb.md

Altinn/app-frontend-react/issues/11
Altinn/app-frontend-react/pull/47

chore: update changelog for 3.34.2

---

content/community/contributing/handbook/front-end/build/_index.md
content/community/contributing/handbook/front-end/developing/_index.md
content/community/contributing/handbook/test/cypress/_index.md
content/technology/architecture/components/application/construction/altinn-apps/app/app-backend/process/_index.md

Relates to https://github.com/Altinn/altinn-studio/pull/8408

docs: update docs related to app-frontend because the code has moved to a new repository

---

content/community/changelog/app-frontend/v3/whats-new/_index.en.md
content/community/changelog/app-frontend/v3/whats-new/_index.nb.md

Altinn/app-frontend-react/pull/65

chore: update changelog for 3.34.4

---

content/community/changelog/app-frontend/v3/whats-new/_index.en.md
content/community/changelog/app-frontend/v3/whats-new/_index.nb.md

Relevant change: Altinn/app-frontend-react/pull/69

Change log for 3.35.2

---

content/app/app-dev-course/modul1/_index.nb.md

Looking forward to tomorrow! :partying_face:

App dev course: Using absolute path to access file

---

content/app/app-dev-course/losningsforslag/_index.nb.md

fixed broken image url

---

content/app/app-dev-course/case/_index.nb.md

minor case fixes

---

content/community/changelog/app-frontend/v3/whats-new/_index.en.md
content/community/changelog/app-frontend/v3/whats-new/_index.nb.md

Docs for Altinn/app-frontend-react/pull/81 and Altinn/app-frontend-react/pull/78

Change log for 3.36.2

---

content/community/changelog/app-frontend/v3/whats-new/_index.en.md
content/community/changelog/app-frontend/v3/whats-new/_index.nb.md

For PR: Altinn/app-frontend-react/pull/82

Change log for 3.36.4

---

content/app/development/configuration/queryparameters/_index.en.md
content/app/development/configuration/queryparameters/_index.nb.md

Rename the norwegian file from .no to .nb so it'll actually work.
Add documentation regarding base64

Add documentation regarding base64 for returnUrl query param

---

content/community/changelog/app-frontend/v3/whats-new/_index.en.md
content/community/changelog/app-frontend/v3/whats-new/_index.nb.md

Related PRs:
- Altinn/app-frontend-react#87 (3.37.1)
- Altinn/app-frontend-react#74 (3.37.0)

Change log for 3.37.0 and 3.37.1

---

content/community/devops/definition-of-ready/_index.en.md
content/community/devops/definition-of-ready/_index.no.md

First attempt at describing our definition of ready - ie. what does it take to get a user story started on by the development team.

feat: add definition of ready descripton

---

content/app/development/ux/pages/tracks/_index.en.md
content/app/development/ux/pages/tracks/_index.nb.md

Part of Altinn/app-frontend-react#127
Updated docs that should be merged after
- https://github.com/Altinn/app-template-dotnet/pull/81
- https://github.com/Altinn/app-frontend-react/pull/74

updated docs for tracks after issue 8347 is solved

---

content/community/changelog/app-nuget/v6/_index.en.md
content/community/changelog/app-nuget/v6/_index.nb.md
content/community/changelog/app-nuget/v6/whats-new/_index.nb.md

Changed headings for v6 changelog which said v4.

Fix headings for v6

---

content/community/changelog/app-nuget/v5/whats-new/_index.en.md
content/community/changelog/app-nuget/v5/whats-new/_index.nb.md
content/community/changelog/app-nuget/v6/breaking-changes/_index.en.md
content/community/changelog/app-nuget/v6/breaking-changes/_index.nb.md

Added missing v5.2.0 doc
Cleaned up v6 doc to match implementation.

Add missing v5.2.0 doc and fix some issues on v6 page

---

content/api/authentication/maskinporten/_index.nb.md

Fix description

---

content/app/app-dev-course/modul3/_index.nb.md
content/community/changelog/app-nuget/v5/whats-new/_index.en.md
content/community/changelog/app-nuget/v5/whats-new/_index.nb.md
content/community/changelog/storage-interfaces/v3/_index.en.md
content/community/changelog/storage-interfaces/v3/_index.nb.md
static/swagger/altinn-platform-storage-v1.json

documented changes in feature/14

---

static/swagger/altinn-app-v1.json

The link to app specific OpenAPI specification is wrong.

Fix swagger link

---

content/app/development/configuration/process/auto-delete/_index.en.md
content/app/development/configuration/process/auto-delete/_index.nb.md

auto delete docs

---

content/app/development/logic/validation/_index.en.md
content/app/development/logic/validation/_index.nb.md

Updatedhttps://github.com/Altinn/app-frontend-react/issues/130 documentation for changes done for

docs for required fields error message

---

content/technology/architecture/capabilities/runtime/security/authorization/authorizationdetailed2026.drawio.svg

component update

---

content/community/changelog/app-nuget/v6/_index.en.md
content/community/changelog/app-nuget/v6/_index.nb.md
content/community/changelog/app-nuget/v6/breaking-changes/_index.en.md
content/community/changelog/app-nuget/v6/breaking-changes/_index.nb.md

Updates to the documentation for .Net 6 upgrade of apps.

Add doc to install .Net 6 SDK first.

---

content/community/changelog/app-nuget/v6/breaking-changes/_index.en.md
content/community/changelog/app-nuget/v6/breaking-changes/_index.nb.md

Change reference to dotnet image that was targeting a non existing patch image.

Update ref. to dot image fra 6.0.102 to 6.0

---

content/app/launched-apps/_index.en.md
content/app/launched-apps/_index.nb.md

Brønnøysundregistrene lanserer oppstartsveilederenfor innlogget og ikke innlogget bruker.

Ny tjeneste juli 2022

---

content/technology/architecture/components/application/solution/altinn-platform/authorization/_index.md
content/technology/architecture/components/application/solution/altinn-platform/authorization/authorizationdetailed2026.drawio.svg
content/technology/architecture/components/application/solution/altinn-platform/authorization/serviceregistry/policysample3 copy.xml

Some more updates

---

content/app/design/guidelines/components/select/_index.en.md

Translated norwegian doc. to english
- #553 
No changes to code, only documentation

Translate "Nedtrekksliste" into "Pull-down list"

---

content/app/design/guidelines/components/checkbox/_index.en.md

Translated norwegian doc into english
- #553 
No changes to code

Translate "Avkrysningsboks" into "Choice box"

---

content/app/design/guidelines/components/error-message/_index.en.md

Unsure of the usage of "NB" on line 20, migth be correct to use "PS"
Translation from nb to en
- #553 
No changes to code only to text in documentation

Translate "Feilmeldinger" into "Error messages"

---

content/app/design/guidelines/tone-of-voice/_index.en.md

Examples on line 51 need to be updated, using verbal nouns might make more sence in english than norwegian
Translated from nb to en
- #553 
No changes to code, only documentation

translate "Språk" into "Language"

---

content/app/design/guidelines/components/button/_index.en.md

Translated "knapp og lenge" from norwegian to english
translation nb to en
- #553 
No changes to code, only text

"Knapp og lenke" translated to "Button and link"

---

content/app/design/guidelines/components/input/_index.en.md

Translated "Input" (nb) to "Input" (en)
- #553 
no changes to code

Translated "Input" (nb) to "Input" (en)

---

content/app/design/guidelines/components/file-upload/_index.en.md

translated from nb to en 
"example of use" should probably be changed to "Example of use"
- #553 
no changes to code, only to documentation.

Translate "Filopplastning" into "File upload"

---

content/app/design/guidelines/components/date/_index.en.md

Translated "Dato" page into "Date" 
- #553 
No code has been altered, only changes to text in the documentation

Translated "Dato" to "Date"

---

content/app/launched-apps/_index.en.md
content/app/launched-apps/_index.nb.md

The Labour Inspection Authority deployed a new Altinn 3.0 app. 

Launched apps June 2022. Update _index.en.md

---

content/app/app-dev-course/case/_index.en.md
content/app/app-dev-course/modul1/_index.en.md
content/app/app-dev-course/modul2/_index.en.md
content/app/app-dev-course/modul3/_index.en.md
content/app/app-dev-course/modul4/_index.en.md
content/app/app-dev-course/modul5/_index.en.md
content/app/app-dev-course/modul6/_index.en.md
content/app/app-dev-course/modul7/_index.en.md

oversettelse introkurs (engelsk)

---

content/app/design/guidelines/components/helptext/_index.en.md

Translation to english, put more emphasis on not using helper texts as containers of vital informatio.n 
- #553 
No changes to code, only translation of documentation

Translate "Hjelpetext" to "Helper texts"

---

content/app/development/configuration/process/auto-delete/_index.en.md

Translate "auto-delete"

---

content/app/app-dev-course/modul4/_index.en.md
content/app/design/usertest/_index.en.md

Build errors in previous commits stopping release of updates to docs

fixed build errors

---

content/app/development/configuration/partytype/_index.en.md

- #553 
No changes to code, only documentation

Finish translation of "Party types"

---

content/app/development/api/instance/_index.en.md

This page would benefit from clarifying/rewriting some parts (esp. step 2 and 3)

Finish translating "Instance"

---

content/app/development/configuration/datafields/_index.en.md

Translate datafields to english

---

content/app/development/configuration/settings/_index.en.md

Translated "Settings and environmental variables"

---

content/app/development/configuration/events/_index.en.md

translate "Events"

---

content/app/development/configuration/secrets/_index.en.md

Translate "secrets"

---

content/app/development/configuration/stateless/_index.en.md

This page should probably be split into multiple pages for the different sections

Translate "Stateless"

---

content/app/design/guidelines/wcag/_index.en.md

translated from nb to en
- #553 
no code changes, only documentation

Translate "Tilgjengelighet" into "Accessibility"

---

content/app/development/configuration/authentication/_index.en.md

translate "Configuration of authentification"

---

content/technology/architecture/capabilities/runtime/integration/events/_index.md
content/technology/architecture/components/application/construction/altinn-platform/events/_index.md
content/technology/architecture/components/application/solution/altinn-platform/events/_index.md

Minor updated to events documentation 
- altinn/altinn-events#6

Minor updated to events documentation 

---

i18n/en.yaml
i18n/nb.yaml
layouts/partials/blocks/api.html

Include events in API block on front page. Removed models
- N/A

Include events in API block on front page

---

content/technology/architecture/components/application/solution/altinn-platform/authorization/_index.md
content/technology/architecture/components/application/solution/altinn-platform/authorization/resourceregistry/_index.md
content/technology/architecture/components/application/solution/altinn-platform/authorization/resourceregistry/exampleresource4.json
content/technology/architecture/components/application/solution/altinn-platform/authorization/resourceregistry/policysample4.xml

authz update

---

content/technology/architecture/components/application/solution/altinn-platform/authorization/_index.md
content/technology/architecture/components/application/solution/altinn-platform/authorization/accessgroups/_index.md
content/technology/architecture/components/application/solution/altinn-platform/authorization/accessmanagement/_index.md
content/technology/architecture/components/application/solution/altinn-platform/authorization/accesspolicies/_index.md
content/technology/architecture/components/application/solution/altinn-platform/authorization/authorization_solution_components_future.drawio.svg
content/technology/architecture/components/application/solution/altinn-platform/authorization/resourceregistry/_index.md

authz updates

---

content/community/changelog/app-nuget/v6/whats-new/_index.en.md
content/community/changelog/app-nuget/v6/whats-new/_index.nb.md

Release notes for bugfix release 6.0.1 of nuget packages
- Altinn/app-frontend-react/issues/319
- ~~[ ] Relevant automated test added (if you find this hard, leave it and we'll help out)~~
- ~~[ ] All tests run green~~

Adding release notes for 6.0.1

---

content/community/contributing/handbook/azure-devops/_index.md

Use default children-listing to fix incorrect rendering.

Fix children for azure-devops

---

content/api/authentication/enterpriseuser/_index.en.md

Fix enterpriseuser links

---

content/app/development/data/options/_index.en.md
content/app/development/data/options/_index.nb.md

Docs for https://github.com/Altinn/app-frontend-react/pull/404
- https://github.com/Altinn/app-frontend-react/issues/184

docs: dynamic options  for groups

---

content/app/app-dev-course/modul5/_index.nb.md

Removed an extra "r" in the word "Bekreftelsessteg"
N/A

Fixed a minor typo

---

content/technology/architecture/components/application/solution/altinn-platform/authorization/resourceregistry/_index.md

korrigert lenke til eksempelfil

---

content/app/launched-apps/_index.en.md
content/app/launched-apps/_index.nb.md

Update - Launched apps.

---

content/community/changelog/deployment/v2/whats-new/_index.en.md
content/community/changelog/deployment/v2/whats-new/_index.nb.md

Add release notes for helm chart v2.2.0 and v2.3.0
- https://github.com/altinn/altinn-studio-charts/issues/11

Add release notes for helm chart v2.2.0 and v2.3.0

---

content/app/launched-apps/_index.en.md
content/app/launched-apps/_index.nb.md

Update - Launched apps. Finanstilsynet

---

content/app/development/ux/pages/navigation/_index.en.md
content/app/development/ux/pages/navigation/_index.nb.md

Removes some outdated docs and points to where the use case can be solved.
- Fixed after this caused confusion for [SSB.](https://altinn.slack.com/archives/C02EVE4RU82/p1663152670852329)

docs: update outdated docs on nav

---

content/app/development/ux/pages/layout-sets/_index.en.md
content/app/development/ux/pages/layout-sets/_index.nb.md

see https://github.com/Altinn/app-lib-dotnet/blob/89c3d241a967eaccdb2f03fcce925abd9ecdb361/src/Altinn.App.Core/Configuration/AppSettings.cs#L84

layout-sets.json ends with "s"

---

content/app/app-dev-course/modul3/_index.en.md
content/app/app-dev-course/modul3/_index.nb.md
content/app/app-dev-course/modul4/_index.en.md
content/app/app-dev-course/modul4/_index.nb.md
content/app/development/data/prefill/_index.en.md
content/app/development/data/prefill/_index.nb.md

- Klargjør at man ikke skal instansiere en klasse som allerede er instansiert (modul 2)
- Flytter instruksjon om test til riktig seksjon (modul 3)
- Tydeliggjør hvordan man skal legge til alternativer i modul 4

Utbedrer instruksjoner i introkurs

---

content/app/app-dev-course/case/_index.en.md
content/app/app-dev-course/case/_index.nb.md
content/app/development/api/consume/_index.en.md
content/app/development/api/consume/_index.nb.md
content/community/contributing/_index.en.md

Gjennomførte nylig introkurset (på engelsk) og oppdaget en del skrivefeil / tilfeller av uklar språkbruk rundt om kring i dokumentasjonen. Rettet opp språket de stedene jeg var innom.

Rettelser av skrivefeil/språk

---

content/app/development/configuration/authorization/guidelines_authorization/_index.nb.md

Mindre språklige endringer i Veilednings for autorisasjonsregler.

Språklige endringer i Veiledning for autorisasjonsregler

---

content/app/development/configuration/authorization/guidelines_authorization/_index.nb.md

Oppdatering av tittel

---

content/api/models/data-element/_index.en.md
content/api/models/data-element/_index.nb.md
content/api/models/instance/_index.en.md
content/api/models/instance/_index.nb.md
content/app/testing/local/apitests/org/_index.en.md
content/app/testing/local/apitests/org/_index.nb.md
content/app/testing/local/debug/_index.en.md
content/app/testing/local/debug/_index.nb.md
content/community/contributing/handbook/front-end/developing/_index.md

Simply rewrites URLs from altinn3local.no to local.altinn.cloud
- Altinn/altinn-studio/pull/8957

Rewriting URLs to local.altinn.cloud

---

content/app/development/ux/fields/grouping/alternatives/_index.en.md
content/app/development/ux/fields/grouping/alternatives/_index.nb.md

Update the documentation for openByDefault in repeating groups to describe the new behaviour.
- Altinn/app-frontend-react#396

Update description of openByDefault

---

content/app/development/ux/fields/grouping/alternatives/_index.en.md
content/app/development/ux/fields/grouping/alternatives/_index.nb.md

Added description for "save and open next" button in group edit options.
- Altinn/app-frontend-react#395

Added docs for save and open next button

---

content/app/development/ux/fields/grouping/setup/_index.en.md
content/app/development/ux/fields/grouping/setup/_index.nb.md

Added separate title for table views.
See main PR: https://github.com/Altinn/app-frontend-react/pull/527
- Altinn/app-frontend-react#68

Add tableTitle under textResourceBindings

---

content/app/development/ux/fields/grouping/setup/_index.en.md
content/app/development/ux/fields/grouping/setup/_index.nb.md

Forgot to add the description for changing the default text of the save and open next button in `textResourceBindings` for repeating groups.

Add missing docs for save and open next button

---

content/technology/architecture/components/application/construction/altinn-platform/authorization/accessmanagment/_index.md
content/technology/architecture/components/application/construction/altinn-platform/authorization/accessmanagment/accessmanagement.drawio.svg
content/technology/solutions/altinn-platform/authorization/accessmanagement/_index.md

Some document updates for access managament

access management fix

---

content/app/development/ux/fields/grouping/alternatives/_index.en.md
content/app/development/ux/fields/grouping/alternatives/_index.nb.md

Documentation of how to turn on delete alert popup.
- [#321](https://github.com/Altinn/app-frontend-react/issues/321)
- https://github.com/Altinn/app-frontend-react/pull/498

add description of alertOnDeleteProperty for repeating group settings

---

content/community/changelog/app-nuget/v6/breaking-changes/_index.en.md
content/community/changelog/app-nuget/v6/breaking-changes/_index.nb.md

Remove Alpha Release infobox for Breaking changes App Nuget-pakker i v6.0.0

---

content/app/development/data/prefill/custom/_index.en.md
content/app/development/data/prefill/custom/_index.nb.md
content/app/development/logic/dataprocessing/_index.en.md
content/app/development/logic/dataprocessing/_index.nb.md
content/app/development/logic/validation/_index.en.md
content/app/development/logic/validation/_index.nb.md
content/app/development/ux/pages/tracks/_index.en.md
content/app/development/ux/pages/tracks/_index.nb.md
content/app/development/ux/pdf/_index.en.md
content/app/development/ux/pdf/_index.nb.md

Last addition to version tabs broke our old ways of showing them. Fixing pages with version tabs

Fix version tabs

---

content/technology/solutions/altinn-platform/authorization/migration/_index.md
content/technology/solutions/altinn-platform/authorization/migration/servicemigrationplan/_index.md

Lagt inn plan for migrering av tjenester og annen autorisasjonsfunksjonalitet

Migrationplansv1

---

content/technology/architecture/components/application/construction/altinn-platform/authorization/accessmanagment/_index.md
content/technology/architecture/components/application/construction/altinn-platform/authorization/accessmanagment/dbmodel.drawio.svg

updated data model

---

content/app/getting-started/local-dev/_index.en.md

'Cupy' changed into 'Copy', line 25

'Cupy' changed into 'Copy', line 25

---

content/app/development/logic/validation/_index.en.md
content/app/development/logic/validation/_index.nb.md

Updated docs for group validation to add the new trigger `validateRow`.
- Altinn/app-frontend-react#468
- https://github.com/Altinn/app-frontend-react/pull/594

Updated validation docs for single-row-validation

---

content/technology/solutions/altinn-platform/authorization/accessgroups/type-accessgroups/_index.md

Små språk korrigeringer

---

content/app/development/configuration/authorization/guidelines_authorization/_index.en.md

Update _index.md (#742) (#744)

---

content/app/development/logic/validation/_index.en.md
content/app/development/logic/validation/_index.nb.md

Added note that in order to set validation errors as fixed, you may need to update `appsettings.json`
- https://github.com/Altinn/app-frontend-react/issues/678

Added note about setting validations as fixed

---

content/app/development/logic/validation/_index.en.md
content/app/development/logic/validation/_index.nb.md

- https://github.com/Altinn/app-frontend-react/pull/682

update docs with new RowIndex header

---

content/app/development/logic/expressions/_index.en.md

Update documentation for which properties in which components are able to use expressions.
- https://github.com/Altinn/app-frontend-react/pull/714

update expression docs

---

content/community/devops/teams/authorization/_index.en.md
content/community/devops/teams/authorization/_index.nb.md
content/community/devops/teams/authorization/designfrontendprocess/_index.nb.md
content/technology/solutions/altinn-platform/authorization/accessgroups/_index.md

Lagt til informasjon om autorisasjonsteam

Update _index.md (#776)

---

content/app/development/ux/components/listComponent/_index.en.md

Add english version of list component documentation

---

content/app/app-dev-course/_index.en.md
content/app/app-dev-course/_index.nb.md
content/app/app-dev-course/modul1/_index.en.md
content/app/app-dev-course/modul1/_index.nb.md
content/app/development/configuration/events/_index.en.md
content/app/development/configuration/events/_index.nb.md
content/app/development/configuration/settings/_index.en.md
content/app/development/configuration/settings/_index.nb.md
content/app/getting-started/local-dev/_index.en.md
content/app/getting-started/local-dev/_index.nb.md
content/app/testing/local/_index.en.md
content/app/testing/local/_index.nb.md
content/community/contributing/_index.en.md
content/community/contributing/_index.nb.md
content/community/contributing/handbook/front-end/developing/_index.md
content/community/contributing/handbook/git/_index.md
content/community/contributing/handbook/securecoding/checklist.md
content/technology/architecture/components/application/construction/altinn-studio/altinnstudio_application_construction_architecture.svg
content/technology/architecture/components/application/construction/altinn-studio/designer/backend/_index.md
content/technology/architecture/components/data/logical/logical_data_model.svg

Update paths to reflect new repo structure for folders:
- frontend
- backend
- docs

update paths for frontend, backend and docs folder

---

content/technology/terms/_index.md
i18n/nb.yaml

Read PR side-by-side comparisions to see the general trend of the 42 corrections, most of which are rather obvious. 
No issue.
No real code changed, only text strings.
This IS the documentation.

Corrections to basic technology terms definitions in Altinn Studio Docs 

---

content/app/development/logic/expressions/_index.en.md
content/app/development/logic/expressions/_index.nb.md

- https://github.com/Altinn/app-lib-dotnet/pull/149
- https://github.com/Altinn/app-frontend-react/pull/805

Add docs for ["instanceContext", "instanceOwnerPartyType"]

---

content/app/development/data/prefill/custom/_index.en.md
content/app/development/data/prefill/custom/_index.nb.md

Not sure what to do with instantiation validation. It should probably be mentioned here, but it should probably be looked at together with #798 
- https://github.com/Altinn/altinn-studio-docs/issues/798

Fix namespaces and interface names of IInstatntiationProcessor

---

content/app/development/configuration/process/customize/_index.en.md
content/app/development/configuration/process/customize/_index.nb.md

Change terminology connected to confirmation documentation to avoid confusion with the actual receipt documentation

Change from receipt to confirmation

---

content/app/development/api/consume/_index.en.md
content/app/development/api/consume/_index.nb.md

including the code line "using Altinn.App.AppLogic.DataProcessing;" in the decription for .NET6.
Included version selector for .NET5 and .NET6.

Update Registrere klienten i applikasjonen .NET 6

---

content/app/launched-apps/_index.nb.md

Oppdatert med prodsatte apper for oktober, november og desember 2022

Oppdatert med nye apper

---

content/app/development/data/options/_index.en.md
content/app/development/data/options/_index.nb.md

Add docs for AddAltinn2CodeList
- https://github.com/Altinn/app-template-dotnet/pull/26

Document the usage of AddAltinn2CodeList

---

content/app/development/ux/components/listComponent/_index.en.md
content/app/development/ux/components/listComponent/_index.nb.md

Noen endringer i dokumentasjonen etter endringer i listekomponenten ifm mobiltilpasning. 

Update documentation of list component after adding mobile view

---

content/api/models/app-metadata/_index.en.md
content/api/models/app-metadata/_index.nb.md

Document onEntry and CopyInstanceSettings in applicationmetadata.json
Fixes #806

Document onEntry and CopyInstanceSettings in applicationmetadata.json

---

content/app/development/configuration/stateless/_index.en.md
content/app/development/configuration/stateless/_index.nb.md

link to nuget for stateless app. Eng and Nb.

link to nuget

---

content/app/development/configuration/authorization/rules/_index.en.md
content/app/development/configuration/authorization/rules/_index.nb.md

Oppdater dokumentasjon etter 
- https://github.com/Altinn/altinn-studio/issues/9461

Nevn at det ikke lenger er nødvendig å erstatte [ORG] og [APP]

---

content/app/launched-apps/_index.en.md
content/app/launched-apps/_index.nb.md

Helse Møre og Romsdal
Migrert tjeneste fra 2.0 til 3.0 - Melding om samhandlingsavvik

ny lansert tjeneste.

---

content/api/models/app-metadata/_index.en.md
content/api/models/app-metadata/_index.nb.md

* Documented new settings on DataType in ApplicationMetadata
- https://github.com/Altinn/altinn-file-scan/issues/1

File scanning of uploaded files in applications

---

static/swagger/altinn-app-v1.json
static/swagger/altinn-platform-storage-v1.json

Updated open api specs for storage and app

updated open api specs

---

content/api/apps/instances/_index.en.md
content/api/apps/instances/_index.nb.md

This was not obvious from context.

SimpleInstantiation.prefil is a Dictionary<string,string>

---

content/app/design/_index.en.md

Added missing alias for old design folder ( English )

Added missing alias for old design folder ( English )

---

content/app/design/_index.nb.md

Added missing aliases for old design folder

Added missing alias for old design folder

---

content/app/app-dev-course/_index.en.md
content/app/app-dev-course/_index.nb.md
content/app/app-dev-course/modul1/_index.en.md
content/app/app-dev-course/modul1/_index.nb.md
content/app/development/configuration/events/_index.en.md
content/app/development/configuration/events/_index.nb.md
content/app/development/configuration/settings/_index.en.md
content/app/development/configuration/settings/_index.nb.md
content/app/getting-started/local-dev/_index.en.md
content/app/getting-started/local-dev/_index.nb.md
content/app/testing/local/_index.en.md
content/app/testing/local/_index.nb.md
content/community/contributing/handbook/front-end/developing/_index.md

LocalTest have moved out of the `altinn-studio` repo and into it's own at: https://github.com/Altinn/app-localtest/blob/master/README.md

moving localtest to new repo

---

content/app/development/ux/pdf/_index.en.md
content/app/development/ux/pdf/_index.nb.md

This documents how to enable and configure the new PDF feature within an app.
- https://github.com/Altinn/app-lib-dotnet/issues/153

Add doc on new PDF service

---

content/app/development/ux/pdf/local-development/_index.en.md
content/app/development/ux/pdf/local-development/_index.nb.md

Adds documentation on how to configure new pdf service for local development
- https://github.com/Altinn/app-lib-dotnet/issues/153

Added page on how to setup new pdf service for local development

---

content/app/monitoring/_index.en.md
content/app/monitoring/_index.nb.md
content/app/monitoring/faq/_index.en.md
content/app/monitoring/faq/_index.nb.md

added info about what we monitor in FAQ

---

content/app/development/ux/pages/navigation/_index.en.md
content/app/development/ux/pages/navigation/_index.nb.md

Updated navigationbar docs to include recent added property option "compact"
https://github.com/Altinn/app-frontend-react/pull/935

Update navbar docs

---

content/app/development/logic/expressions/_index.en.md
content/app/development/logic/expressions/_index.nb.md

Some adjustments and language cleanup in expressions docs

Minor fixes in expressions doc

---

content/app/development/ux/pdf/_index.en.md
content/app/development/ux/pdf/_index.nb.md

Is this correct?
- https://github.com/Altinn/app-lib-dotnet/pull/194

Updated default pdf url

---

content/app/development/ux/texts/_index.en.md
content/app/development/ux/texts/_index.nb.md

- https://github.com/Altinn/app-frontend-react/pull/893

Adding docs about opening links in the same window

---

content/app/development/ux/pdf/_index.en.md

Fix typo in `IPdfFormatter`

---

content/app/testing/local/testusers/_index.en.md
content/app/testing/local/testusers/_index.nb.md

Added docs for new roles in the test data, and updated urls to point to new app-localtest repo.
- https://github.com/Altinn/app-localtest/pull/27

added docs for new roles and updated urls

---

content/community/changelog/app-nuget/v7/breaking-changes/_index.nb.md

Changing the method from HandleTaskEnd to End. 
IProcessTaskEnd.cs contain the Task End. 
https://github.com/Altinn/app-lib-dotnet/blob/main/src/Altinn.App.Core/Features/IProcessTaskEnd.cs

Breaking changes v7

---

content/community/changelog/deployment/migration/_index.en.md
content/community/changelog/deployment/migration/_index.nb.md
content/community/changelog/deployment/v2/whats-new/_index.en.md
content/community/changelog/deployment/v2/whats-new/_index.nb.md

* Update changelog deployment v2.6.0-v2.8.0

Update changelog deployment v2.6.0-v2.8.0

---

static/swagger/altinn-platform-events-v1.json

updated events swagger

---

content/app/development/ux/footer/_index.nb.md

Overlooked a couple of translations to nb.

Updated missing translations

---

content/app/development/ux/components/listComponent/_index.en.md
content/app/development/ux/components/listComponent/_index.nb.md

User was struggling, the issue was missing service registration. Update the docs to include these instructions

Add missing service registration documentation for listcomponent

---

content/app/development/ux/pages/_index.en.md
content/app/development/ux/pages/_index.nb.md

Updated the pages docs to include all of the currently supported page settings, and removed very old guide for upgrading to version 1.2.0 to get multiple pages as I doubt that is very useful anymore.
- https://github.com/Altinn/app-frontend-react/issues/95

Updated pages docs to be more up to date

---

content/app/development/logic/dynamic/_index.en.md
content/app/development/logic/dynamic/_index.nb.md

Clean up spelling and punctuation

---

deploy.ps1

Deploy.ps1 was deleted by mistake.

Re-introduce deploy.ps1

---

content/app/development/logic/expressions/_index.en.md
content/app/development/logic/expressions/_index.nb.md
content/app/development/ux/fields/grouping/alternatives/_index.en.md
content/app/development/ux/fields/grouping/alternatives/_index.nb.md
content/app/development/ux/fields/grouping/repeating/_index.en.md
content/app/development/ux/fields/grouping/repeating/_index.nb.md

Docs for the new property "hiddenRow".

Docs for the new hiddenRow property for repearting groups

---

content/app/maintainance/dependencies/_index.en.md
content/app/maintainance/dependencies/_index.nb.md

A tiny update to maintenance instructions to avoid possible misunderstanding about what version to upgrade to.

Update chart version in maintainance instructions

---

content/app/development/configuration/process/customize/_index.en.md
content/app/development/configuration/process/customize/_index.nb.md

See linked issue for further explanation.
- https://github.com/Altinn/app-frontend-react/pull/1058

Added info about setting receiver in receipt

---

content/api/authentication/digdirscopes/_index.en.md
content/api/authentication/digdirscopes/_index.nb.md
content/technology/architecture/capabilities/devops/softwareconfiguration/_index.md
content/technology/architecture/components/infrastructure/computing/_index.md

scopes changes

---

content/app/development/data/options/_index.en.md
content/app/development/data/options/_index.nb.md

Add docs for description and helptext for options

Add docs for description and helptext for options

---

content/community/contributing/handbook/front-end/new-component/_index.md

Added new prop to render as summary
- [#996](https://github.com/Altinn/app-frontend-react/issues/996)

Added new prop to render as summary

---

content/app/development/ux/fields/grouping/non-repeating/_index.en.md
content/app/development/ux/fields/grouping/non-repeating/_index.nb.md

- https://github.com/Altinn/app-frontend-react/pull/1200

Add docs for grouping indicator for non-rep groups

---

content/app/development/ux/components/iframe/index.en.md
content/app/development/ux/components/iframe/index.nb.md

Docs for configuring the new sandbox property on the IFrame component.
- https://github.com/Altinn/app-frontend-react/pull/1221

Docs for iframe sandbox

---

content/app/development/ux/fields/settings/_index.en.md

Documentation for countdown feature.
Feature is implemented within this PR:
https://github.com/Altinn/app-frontend-react/pull/1193
https://github.com/Altinn/app-frontend-react/issues/565

Documentation for countdown feature.

---

content/app/app-dev-course/_index.en.md

Updated the first page of the Intro Course to match the updated Norwegian version.

Updated app-dev-course _index.en.md to match _index.nb.md.

---

content/app/app-dev-course/modul1/_index.en.md

Updated English version of Module 1 index file to reflect changes made in the Norwegian version.

Updated app-dev-course Module 1_index.en.md to match _index.nb.md.

---

content/app/guides/access-management/apps/_index.en.md
content/app/guides/access-management/apps/_index.nb.md
content/app/monitoring/prerequisites/_index.en.md
content/app/monitoring/prerequisites/_index.nb.md

Applied changes made by @MWold in PR #874.
The folders enclosing the changed files had been moved and the PR could therefore not be merged.

Update and add english translation for app infrastructure page

---

content/app/app-dev-course/modul1/_index.en.md
content/app/app-dev-course/modul1/_index.nb.md
content/app/development/data/data-model/data-models-tool/_index.nb.md

- Rewritten part of the content for clarification
- Added description of model files (taken from [Intro Course Mudule 1 Solution](https://docs.altinn.studio/nb/app/app-dev-course/losningsforslag/#det-er-blitt-generert-en-_c_-_metadatajson_-og-_schemajson_-fil-i-tillegg-til-_xsd_-filen-som-du-lastet-opp-hva-er-sammenhengen-mellom-disse-filene)).

Update data-models-tool index nb

---

content/app/development/data/data-model/data-models-tool/_index.nb.md

More updates to data-models-tool _index.nb.md

---

content/authorization/architecture/resourceregistry/actionoptions.json

fixed trailing comma

---

content/app/development/logic/expressions/_index.en.md
content/app/development/logic/expressions/_index.nb.md

Documentation for Newly Added Expressions Functions
- https://github.com/Altinn/app-frontend-react/issues/1176

Documentation for newly added expressions functions

---

content/app/getting-started/local-dev/_index.en.md
content/app/getting-started/local-dev/_index.nb.md

Updated _index.en.md to match Norwegian version plus minor changes to _index.nb.md

---

content/app/getting-started/local-dev/_index.en.md
content/app/getting-started/local-dev/_index.nb.md

Included 'Preview and test application' as the third step under Local testing.

Small structural modification

---

content/app/development/configuration/eformidling/_index.en.md
content/app/development/configuration/eformidling/_index.nb.md

Necessary configuration to enable DPO has been deployed in all environments.
- https://github.com/Altinn/altinn-platform/issues/500

Make it clear that DPO (eFormidling) is available

---

content/app/app-dev-course/modul1/_index.en.md
content/app/app-dev-course/modul1/_index.nb.md

Minor edits to module 1 index files

---

content/app/app-dev-course/_index.en.md
content/app/app-dev-course/_index.nb.md

Replaced 'points' with 'steps'

Small grammatical change

---

content/app/development/ux/pages/navigation/_index.en.md
content/app/development/ux/pages/navigation/_index.nb.md

I guess some automatic formatting changed some lines as well. Actual changes are just the very bottom of each file.
- https://github.com/Altinn/app-frontend-react/pull/1229

Docs for new validation trigger

---

content/authorization/_index.md
content/authorization/architecture/resourceregistry/migration_flow.drawio.svg

added aliases

---

content/app/app_structure.drawio.svg

Updated structure diagram - suggestion for new app structure

Updated new structure

---

content/app/guides/access-management/_index.en.md
content/app/guides/access-management/_index.nb.md
content/app/guides/copy-app/_index.en.md
content/app/guides/copy-app/_index.nb.md
content/app/guides/design/_index.en.md
content/app/guides/design/_index.nb.md
content/app/guides/design/guidelines/_index.en.md
content/app/guides/design/guidelines/_index.nb.md
content/app/guides/design/guidelines/components/_index.en.md
content/app/guides/design/guidelines/components/_index.nb.md
content/app/guides/migrate-services/_index.en.md
content/app/guides/migrate-services/_index.nb.md
content/app/guides/testing/_index.en.md
content/app/guides/testing/_index.nb.md
content/app/guides/testing/deploy/_index.en.md
content/app/guides/testing/deploy/_index.nb.md
content/app/guides/testing/local/_index.en.md
content/app/guides/testing/local/_index.nb.md

Added aliases for moved folders

---

content/app/development/configuration/shadowfields/_index.en.md
content/app/development/configuration/shadowfields/_index.nb.md

Updated shadow fields documentation with:
- Note about which version of the nuget packages are compatible
- Specification on how to update data model fields
- https://github.com/Altinn/altinn-studio/issues/10108

updated docs after testing feedback

---

content/app/development/ux/components/grid/_index.en.md
content/app/development/ux/components/grid/_index.nb.md

Clarification for text cells in Grid

---

content/app/development/data/attachments/_index.en.md
content/app/development/data/attachments/_index.nb.md

Add alertOnDelete option to uploaded attachments
https://github.com/Altinn/app-frontend-react/pull/1253

alertOnDelete on attachment

---

content/app/development/ux/pages/summary/_index.en.md
content/app/development/ux/pages/summary/_index.nb.md

Updated the description of text resources used in summary. 
https://github.com/Altinn/app-frontend-react/pull/1278

summaryTitle and summaryAccessibleTitle

---

content/app/development/ux/components/checkbox/_index.en.md

Replaced expand with normal heading for Usage, replaced props table with list of component props.

Update checkbox docs

---

content/app/development/ux/fields/grouping/repeating/_index.en.md
content/app/development/ux/fields/grouping/repeating/_index.nb.md

Add minCount to properties for repeating groups documentation

Update docs for repeating groups minCount

---

content/app/app-dev-course/modul1/_index.en.md
content/app/app-dev-course/modul1/_index.nb.md

Added 'next module' link at the bottom

---

content/app/development/configuration/authorization/guidelines_authorization/roles_and_rights/roles_ER/_index.nb.md
content/authorization/modules/accessgroups/register_ER/_index.md
content/authorization/modules/accessgroups/type-accessgroups/_index.md

Lagt til informasjon om orgform og roller som benyttes i autorisasjon

Oppdatert info om plan for migrering av tjenester

---

config.toml
themes/hugo-theme-altinn/layouts/shortcodes/common-defs-expandlarge.html
themes/hugo-theme-altinn/layouts/shortcodes/component-props.html
themes/hugo-theme-altinn/layouts/shortcodes/componentProps-functions/follow-reference.html
themes/hugo-theme-altinn/layouts/shortcodes/componentProps-functions/formatAnyAllOneOf.html
themes/hugo-theme-altinn/layouts/shortcodes/componentProps-functions/formatAsCode.html
themes/hugo-theme-altinn/layouts/shortcodes/componentProps-functions/list-descriptions.html
themes/hugo-theme-altinn/layouts/shortcodes/componentProps-functions/list-properties.html
themes/hugo-theme-altinn/layouts/shortcodes/title.html

* Several shortcode files that automatically generate properties description from the component's schema file (linked to files currently in drafted PR #1283)
* Shortcode to print page title

Component props shortcode

---

content/authorization/modules/accessgroups/register_ER/_index.md
content/authorization/modules/accessgroups/register_ER/knytning_org/_index.md

Laget oversikt over orgformer og roller fra ER

Laget oversikt over orgformer og roller fra ER

---

content/app/development/logic/expressions/_index.en.md
content/app/development/logic/expressions/_index.nb.md

Docs for new displayValue expression. Looks like the file got formatted as well, let me know if you want it back the way it was.
- https://github.com/Altinn/app-frontend-react/pull/1341

Added docs for displayValue expression

---

themes/hugo-theme-altinn/layouts/shortcodes/expand.html

Added hugo config version to expand shortcode so it works with '%'

---

themes/hugo-theme-altinn/layouts/shortcodes/expandbold.html

Created a version of the `expand` shortcode with a slightly larger arrow and bold header.

Created expandbold shortcode

---

content/app/development/configuration/startup/_index.en.md
content/app/development/configuration/startup/_index.nb.md

Typo - version 7.12.0, not 7.13.0

---

content/app/development/configuration/startup/_index.en.md
content/app/development/configuration/startup/_index.nb.md

Asc sorting instances as default

---

static/css/custom.css
themes/hugo-theme-altinn/layouts/shortcodes/component-props.html
themes/hugo-theme-altinn/layouts/shortcodes/componentProps-functions/follow-reference.html
themes/hugo-theme-altinn/layouts/shortcodes/componentProps-functions/list-properties.html

Updated formatting for component properties list.

Update properties shortcode

---

content/app/development/ux/components/images/_index.en.md

Corrected path for wwwroot folder

---

static/css/custom.css

Custom css for tabs. Thin, full tab border and full-width content

---

content/app/development/ux/components/images/_index.en.md

- Display tabs as buttons
- Full-width tab container content

Added class thin-border-tabs to Code-ASD tabs

---

themes/hugo-theme-altinn/layouts/shortcodes/expandbold.html

Add light gray background to expand content

---

themes/hugo-theme-altinn/layouts/shortcodes/gray-divider-line.html

Shortcode that adds a horizontal gray divider line

---

static/css/custom.css

Update custom.css with class 'thin-border' for tabs

---

themes/hugo-theme-altinn/layouts/shortcodes/center.html

Created shortcode to center content

---

themes/hugo-theme-altinn/layouts/shortcodes/center.html

Add markdownify to center shortcode

---

themes/hugo-theme-altinn/layouts/shortcodes/markdown.html

Create shortcode that markdownifies content

---

content/authorization/migration/servicemigrationplan/_index.md

Oppdatert plan for migrering av tjenester

Oppdatert plan for migrering av tjenester

---

content/app/app-dev-course/_index.en.md
content/app/app-dev-course/_index.nb.md

Added notice about course update to main pages

---

content/app/app-dev-course/modul2/_index.nb.md

Updated text and formatting.
- #1005

Updated text and formatting in module 2 (nb)

---

content/app/app-dev-course/modul2/_index.en.md

Updated English version of module 2 to match updated Norwegian version.
- #1005

Updated module 2 (en) to match Norwegian version

---

content/app/development/logic/services/_index.en.md
content/app/development/logic/services/_index.nb.md

Documented minimum auth level requirement for person lookup service in app

added warning for person lookup

---

content/app/app-dev-course/modul2/_index.en.md

Update language in module 2 (en)

---

content/app/app-dev-course/modul2/_index.en.md
content/app/app-dev-course/modul2/_index.nb.md

- Fixed spelling mistakes
- Improved language
- #1005

Module2 update

---

themes/hugo-theme-altinn/layouts/shortcodes/expandbold.html

Markdownify label and content

---

content/app/app-dev-course/losningsforslag/_index.en.md
content/app/app-dev-course/losningsforslag/_index.nb.md
content/app/app-dev-course/modul1/_index.en.md
content/app/app-dev-course/modul1/_index.nb.md
content/app/app-dev-course/modul2/_index.en.md
content/app/app-dev-course/modul2/_index.nb.md

- Updated the structure and language of module 1 (en and nb)
- Made some small changes to Module 2 files
- Added notice to Solution about update in progress
- #1005

Introcourse update (M1 and M2)

---

content/app/development/ux/components/images/_index.en.md

- Removed notice about image component not being included in pdf
- add notice about config updates in Designer
- Text updates (grammar etc)
- #{}

Removed notice about image not being included in pdf, add notice about config updates ++

---

content/authorization/modules/resourceregistry/_index.md

Ferdigstilt versjon 2 av attributter på ressurser

Siv_180823

---

content/app/development/configuration/autoSaveBehavior/_index.en.md

Adding docs for new feature: https://github.com/Altinn/app-frontend-react/pull/1162

Add docs for auto save behavior

---

content/app/launched-apps/external/_index.en.md

Tjenester for februar-juli 2023

Oppdatert med nye tjenester

---

content/app/development/data/options/_index.nb.md
content/app/development/ux/pages/navigation/_index.en.md
content/app/development/ux/pages/navigation/_index.nb.md
content/app/development/ux/pages/summary/_index.en.md
content/app/development/ux/pages/summary/_index.nb.md
content/app/development/ux/texts/_index.en.md
content/app/development/ux/texts/_index.nb.md
content/community/changelog/app-frontend/stricter-schema/_index.en.md
content/community/changelog/app-frontend/stricter-schema/_index.nb.md
content/community/changelog/app-frontend/v3/whats-new/_index.en.md
content/community/changelog/app-frontend/v3/whats-new/_index.nb.md
content/community/contributing/handbook/front-end/new-component/_index.md

Adding docs to give examples for app developers about what to expect when the JsonSchema changes hit
- https://github.com/Altinn/app-frontend-react/pull/1406

New docs page for layout JsonSchema changes

---

static/css/custom.css

- Styling of h2, h3 and h4 code 

Custom css for code titles

---

themes/hugo-theme-altinn/layouts/shortcodes/expandsmall.html

Similiar to expandbold, only smaller and with no divider lines.

Added expandsmall shortcode

---

static/css/custom.css
themes/hugo-theme-altinn/layouts/shortcodes/expandbold.html
themes/hugo-theme-altinn/static/css/theme.css

- Add a bit of top margin to circle list
- Add top and bottom margins to expandbold
- Styling of expandsmall

Circle list and expand css

---

content/app/app-dev-course/modul1/_index.en.md
content/app/app-dev-course/modul1/_index.nb.md
content/app/app-dev-course/modul2/_index.en.md
content/app/app-dev-course/modul2/_index.nb.md

Replace expandbold shortcode with expandsmall shortcode in modules 1 and 2

---

themes/hugo-theme-altinn/static/css/theme.css

- Updated styling of code in links (unset color, no background, border, or copy-to-clipboard)

Styling of code in links

---

content/app/app-dev-course/modul3/_index.en.md
content/app/development/configuration/deployment/_index.en.md
content/app/development/configuration/deployment/_index.nb.md

- Small grammatical and structural changes to Norwegian docs
- Updated English docs to match Norwegian docs

Update deployment docs (en)

---

content/app/app-dev-course/modul3/_index.en.md
content/app/app-dev-course/modul3/_index.nb.md

Introcourse module3 update

---

content/events/publish-events/developer-guides/publish-events/_index.en.md
content/events/subscribe-to-events/developer-guides/query-events/_index.en.md
content/events/subscribe-to-events/developer-guides/setup-subscription/_index.en.md

Updated documentation on events

updated events doc to include resource

---

content/community/about/open-source/_index.en.md
content/community/about/open-source/_index.nb.md

fixed link to external contributions

---

content/app/development/ux/components/Checkboxes/_index.en.md
content/app/development/ux/components/Checkboxes/_index.nb.md
content/app/development/ux/components/radioButtons/_index.en.md
content/app/development/ux/components/radioButtons/_index.nb.md

Correct 'Related' section for RadioButtons and Checkboxes

---

content/app/development/ux/components/Checkboxes/_index.en.md

Fix missed translation of sentence

---

content/community/contributing/handbook/back-end/nuget-package/_index.md

Updated developer handbook with doc for enabling nuget creation both automatic and manual

updated doc on nuget package creation

---

content/authorization/architecture/resourceregistry/subjectoptions.json

updates subjects

---

content/app/development/ux/components/_common-props-content/_INSTRUCTIONS.md
content/app/development/ux/components/_common-props-content/_TEMPLATE.md
layouts/partials/component-props/tabs.html
layouts/shortcodes/property-docs.html

- Shortcode and template updates
- #1007

Update common props shortcode

---

content/community/changelog/deployment/v3/_index.en.md
content/community/changelog/deployment/v3/_index.nb.md
content/community/changelog/deployment/v3/breaking-changes/_index.en.md
content/community/changelog/deployment/v3/breaking-changes/_index.nb.md
content/community/changelog/deployment/v3/whats-new/_index.en.md
content/community/changelog/deployment/v3/whats-new/_index.nb.md

* Update helm deployment release note v3.0.0

Update helm deployment release note v3.0.0

---

content/community/changelog/deployment/v3/whats-new/_index.en.md
content/community/changelog/deployment/v3/whats-new/_index.nb.md

* Add release note deployment 3.0.1

Add release note deployment 3.0.1

---

content/authentication/systemauthentication/_index.md

updates description

---

content/authorization/modules/accessgroups/type-accessgroups/versjon-2/forhold/_index.md

Updated description of access group

---

content/app/development/logic/expressions/_index.en.md
content/app/development/logic/expressions/_index.nb.md

- https://github.com/Altinn/app-lib-dotnet/pull/277

Update backend expression availability overview

---

content/authorization/modules/accessgroups/type-accessgroups/versjon-2/personale/_index.md

Replaced STYR with LEDE

---

content/broker/_index.en.md
content/broker/_index.nb.md

The very first start with broker doc

Tore-okt-10

---

content/app/app-dev-course/modul5/_index.nb.md

Fix formatting

---

i18n/en.yaml
i18n/nb.yaml
layouts/partials/topbar.html
static/css/custom.css
themes/hugo-theme-altinn/layouts/partials/menu.html
themes/hugo-theme-altinn/layouts/partials/search.html
themes/hugo-theme-altinn/static/css/horsey.css
themes/hugo-theme-altinn/static/css/theme.css
themes/hugo-theme-altinn/static/js/search.js

- Moved search into top menu
- Show flag icon in top menu
- Checkbox for searching across all languages (default on)
- More room for search results
- English
- Norwegian
- Both

Improved search xp

---

themes/hugo-theme-altinn/static/css/horsey.css
themes/hugo-theme-altinn/static/js/search.js

Makes it easier to see what needs translation

Show language in search results

---

content/authorization/modules/accessgroups/type-accessgroups/versjon-2/tilgang/_index.md

presisert at tjenester ikke skal knyttes til gruppene

---

content/authorization/modules/accessgroups/type-accessgroups/versjon-2/forhold/_index.md

Added "drive" in group name

---

content/app/app-dev-course/modul7/_index.nb.md

Fix link to repo

---

content/app/app-dev-course/modul2/_index.en.md
content/app/development/logic/expressions/_index.en.md
content/app/development/ux/pages/navigation/_index.en.md
content/app/development/ux/pages/tracks/_index.en.md

Translated Expressions to english https://docs.altinn.studio/app/development/logic/expressions/#boolske-verdier

Translate expressions to english

---

content/app/development/data/prefill/config/_index.nb.md

Change some text. Corrected some grammar and spelling mistakes.

Change some text. Corrected some grammar and spelling mistakes.

---

content/app/development/configuration/filescan/_index.nb.md

Virus scan nb

---

content/app/development/configuration/messagebox/create_copy/_index.en.md
content/app/development/configuration/messagebox/create_copy/_index.nb.md

Added information about what file to add the configuration to.
- N/A

Added source file to make configuration changes in.

---

content/app/getting-started/create-app/settings/_index.en.md
content/app/getting-started/create-app/settings/_index.nb.md

Added basic documentation for policy editor

---

content/app/development/configuration/stateless/_index.en.md
content/app/development/configuration/stateless/_index.nb.md

Minor text updates, swap 'FormLayout.json' with '{page}.json'

---

content/app/app-dev-course/modul7/_index.nb.md

- Update text for stateless task
- Begin solution (commented out) - needs finishing.
- #1179

Update stateless task

---

content/app/development/logic/expressions/_index.en.md
content/app/development/logic/expressions/_index.nb.md

Remove missleading expression disclaimers

---

content/app/development/logic/validation/_index.en.md
content/app/development/logic/validation/_index.nb.md

Add documentation for usage of the new textResourceBinding `requiredValidation`.

Documentation for requiredValidation text resource binding

---

content/authorization/migration/new-accessgroups/_index.md

Oppdatert info på fremdrift

---

content/app/development/ux/components/_common-props-content/options-page.en.md
content/app/development/ux/components/_common-props-content/options-page.nb.md

Restore content for options-page

---

content/app/app-dev-course/modul4/_index.en.md
content/app/app-dev-course/modul4/_index.nb.md

- Update English version to match Norwegian
- Small updates to Norwegian version
- #1005

Update module 4 nb and en

---

content/app/app-dev-course/modul5/_index.en.md
content/app/app-dev-course/modul5/_index.nb.md

- Small updates to Norwegian version
- Translate/update English version
- #1005

Update introcourse m5 en

---

content/app/app-dev-course/modul6/_index.en.md
content/app/app-dev-course/modul6/_index.nb.md

- Small updates to Norwegian version
- Update/translate English version to correspond to nb
- #1005
- #1337

Update introcourse m6 en

---

content/app/development/configuration/autoSaveBehavior/_index.nb.md

Oversatt Auto Save Behavior til norsk

---

content/authorization/modules/accessgroups/type-accessgroups/versjon-3/post/_index.md

Fixed Post/arkiv

---

content/app/app-dev-course/modul2/_index.nb.md

fixing broken links

---

content/authorization/modules/accessgroups/type-accessgroups/versjon-3/_index.md

Removed "forslag" in title

---

content/authorization/modules/accessgroups/type-accessgroups/versjon-2/jordbruk/_index.md

Added reindrift

---

content/app/getting-started/create-app/process/_index.en.md
content/app/getting-started/create-app/process/_index.nb.md

Added basic documentation on what is currently available in new process editor/viewer.
- https://github.com/Altinn/altinn-studio/issues/11505

basic process editor docs

---

config.toml
themes/hugo-theme-altinn/i18n/en.toml
themes/hugo-theme-altinn/i18n/nb.toml
themes/hugo-theme-altinn/layouts/partials/header.html
themes/hugo-theme-altinn/static/css/theme.css

Added last modified information to all pages based on the git commit date. Feature requested by service owners to be able to validate the relevance of a page and/or if newer information should be available.
- N/A

Add last modified date to pages

---

.github/workflows/hugo.yml
themes/hugo-theme-altinn/theme.toml

Fixes last changed date when using github actions. Ref. https://gohugo.io/methods/page/gitinfo/#hosting-considerations

Deep fetch + hugo patch

---

content/broker/50. Solution Architecture/80. Realization of capabilities and features/20 Authentication and Authorization/_index.en.md

Basic description of our authentication.

Add basic description of authentication

---

content/authorization/linkservicedependencies.drawio.svg
content/authorization/modules/accessgroups/type-accessgroups/_index.md

New drawing

---

content/altinn-studio/architecture/altinnstudio_application_construction_architecture.svg
content/altinn-studio/architecture/designer/designer.drawio.svg
content/community/about/open-source/_index.en.md
content/community/about/open-source/_index.nb.md
content/community/contributing/_index.en.md
content/community/contributing/_index.nb.md
content/community/contributing/handbook/front-end/routine/_index.md
content/community/contributing/handbook/front-end/versioning/_index.md
content/community/contributing/handbook/getting-started/_index.md
content/community/contributing/handbook/git/_index.md
content/technology/architecture/principles/_index.md

Since Studio has updated the main branch from master to main, we needed to change some links and text within the docs. We have also moved the `CONTRIBUTING.md` file to root. I have fixed those links too.
https://github.com/Altinn/altinn-studio/issues/7018

fix(Docs): update docs to reference main instead of master for Studio

---

content/app/development/ux/components/likert/_index.en.md
content/app/development/ux/components/likert/_index.nb.md
content/community/changelog/app-frontend/v4/_index.en.md

Changed `simpleBinding` to `answer` as is correct.

Fix docs for likert datamodelbindings

---

content/app/deployment/_index.en.md
content/app/deployment/_index.nb.md

Update Bestille Om skjema-side

---

content/notifications/architecture/kafka/_index.en.md
content/notifications/architecture/sms/_index.en.md

Update architecture docs for sms

---

content/broker/50. Solution Architecture/80. Realization of capabilities and features/90  API Management/_index.en.md

Some description of how we use APIM.
- #263

Initial documentation on broker APIM

---

content/community/changelog/app-frontend/v4/_index.en.md
content/community/changelog/app-frontend/v4/migrating-from-v3/_index.en.md

- https://github.com/Altinn/app-frontend-react/pull/1761

Docs for app-frontend v4.0.0-rc2

---

.vscode/settings.json
content/notifications/_index.en.md
content/notifications/architecture/_index.en.md
content/notifications/architecture/kafka/_index.en.md
content/notifications/architecture/notifications-topic-process-sms.drawio.svg
content/notifications/architecture/notifications/_index.en.md
content/notifications/architecture/sms/_index.en.md
content/notifications/send-notifications/_index.en.md
content/notifications/send-notifications/developer-guides/get-notification-order-by-id/_index.en.md
content/notifications/send-notifications/developer-guides/get-notification-order-status/_index.en.md
content/notifications/send-notifications/get-started/maskinporten-integration/_index.en.md
content/notifications/send-notifications/get-started/user-guide/_index.en.md
static/swagger/altinn-notifications-v1.json

Documentation on new sms functionality
- altinn/altinn-notifications#373
- altinn/altinn-notifications#364

added documentation for new sms features

---

content/api/storage/instances/_index.en.md
content/api/storage/instances/_index.nb.md

Doc was not matching actual API for the status query params of the GET instances API. Also fixed some typos. 
N/A - doc only

Fixed mismatch between doc and the actual storage instances API.

---

content/notifications/architecture/sms/_index.en.md
content/notifications/architecture/sms/openAPI/_index.en.md
static/swagger/altinn-notifications-sms-v1.json

Documentation notifications-sms-api

---

content/app/cli/_index.en.md
content/app/cli/_index.nb.md
content/app/cli/install/_index.en.md
content/app/cli/install/_index.nb.md
content/community/changelog/app-frontend/v4/migrating-from-v3/_index.en.md
content/community/changelog/app-nuget/v8/migrating-from-v7/_index.en.md
content/community/changelog/app-nuget/v8/migrating-from-v7/_index.nb.md

Altinn Studio CLI upgrade tool

---

content/community/changelog/app-frontend/v4/_index.en.md
content/community/changelog/app-frontend/v4/migrating-from-v3/_index.en.md
content/community/changelog/app-nuget/v8/migrating-from-v7/_index.en.md

Bump versions to latest pre-releases of v4 / v8

Bump upgrade versions

---

content/authorization/modules/accessgroups/type-accessgroups/versjon-3/jordbruk/_index.md

Jordbruk, dyrehold og reindrift

---

content/authorization/modules/pdp/_index.md

doc updates

---

content/events/publish-events/developer-guides/publish-app-events/_index.en.md
content/events/publish-events/developer-guides/publish-events/_index.en.md
content/events/subscribe-to-events/developer-guides/setup-subscription/_index.en.md
content/technology/architecture/components/data/logical/_index.md

Small changes to documentation around alternativesubject in Events
- https://github.com/Altinn/altinn-events/issues/474

Update alternativesubject examples

---

content/authorization/migration/_index.md

Replaced tilgangsgruppe with tilgangspakke

---

content/broker/10. Introduction/_index.en.md
content/broker/20. Requirements/_index.en.md
content/broker/50. Solution Architecture/10. Use Cases Covered/_index.en.md
content/broker/50. Solution Architecture/20. Building blocks and information flow/_index.en.md
content/broker/50. Solution Architecture/50. Transfer Process/_index.en.md
content/broker/50. Solution Architecture/60. Interface Specifications/_index.en.md
content/broker/50. Solution Architecture/80. Realization of capabilities and features/110. Transition architecture during migration window/_index.en.md
content/broker/60. Advanced use cases/_index.en.md
content/broker/70. Possible Future Extensions/_index.en.md

Fixed Broker figure links

---

content/correspondence/10. Introduction/_index.en.md
content/correspondence/20. Requirements/_index.en.md
content/correspondence/30. Architecture Principles/_index.en.md
content/correspondence/40. Technical Standards/_index.en.md
content/correspondence/50. Solution Architecture/_index.en.md
content/correspondence/60. Advanced use cases/_index.en.md
content/correspondence/70. Possible Future Extensions/_index.en.md
content/correspondence/80. Security/_index.en.md
content/correspondence/90. FAQ/_index.en.md
content/correspondence/900. Appendix A - Architecture Decision Log/_index.en.md
content/correspondence/910. Appendix B - Advanced Concepts/_index.en.md
content/correspondence/920. Appendix C - Laws and Regulations/_index.en.md
content/correspondence/930. Appendix D - Research/_index.en.md
content/correspondence/_index.en.md

Correspondence Level 1 skeleton

Correspondence Level 1 skeleton

---

content/app/development/ux/logo/_index.en.md
content/app/development/ux/logo/_index.nb.md

Previously there was no documentation on how to add your own logo to the app and use it. This is added. 
- App Migration issue: https://github.com/Altinn/app-migration/issues/258

added guides for using custom logo in app

---

content/app/development/ux/pdf/_index.en.md
content/app/development/ux/pdf/_index.nb.md

Fixed typos of punctuation and capitalization.

Fixed typos in PDF generation configuration

---

content/community/changelog/app-frontend/v4/_index.en.md
content/community/changelog/app-frontend/v4/migrating-from-v3/_index.en.md
content/community/changelog/app-nuget/v8/migrating-from-v7/_index.en.md

App-frontend v4 and app-backend v8 stable releases

---

content/app/app-dev-course-v2/_index.en.md
content/app/app-dev-course-v2/_index.nb.md
content/app/app-dev-course-v2/case/_index.en.md
content/app/app-dev-course-v2/case/_index.nb.md
content/app/app-dev-course-v2/losningsforslag/_index.en.md
content/app/app-dev-course-v2/losningsforslag/_index.nb.md
content/app/app-dev-course-v2/modul1/_index.en.md
content/app/app-dev-course-v2/modul1/_index.nb.md

Skjule sidene for den oppdaterte kursmodulen foreløpig.

skjule v3 introkurs

---

content/app/app-dev-course-v2/modul1/_index.en.md
content/app/app-dev-course-v2/modul1/_index.nb.md

oppdatert modul1

---

content/app/app-dev-course-v2/modul5/_index.en.md
content/app/app-dev-course-v2/modul5/_index.nb.md

fix missing closing tag

---

content/app/development/logic/dynamic/_index.en.md
content/app/development/logic/dynamic/_index.nb.md

Small fixes to typos, punctuation, formatting and wording.

Fixed typos in dynamics

---

content/notifications/architecture/sms/_index.en.md

Additional architecture documentation

sms arch docs

---

content/app/development/logic/validation/_index.en.md
content/app/development/logic/validation/_index.nb.md
content/community/changelog/app-frontend/v4/_index.en.md

- https://github.com/Altinn/app-frontend-react/pull/1893

Update default showValidations docs

---

content/community/changelog/app-frontend/v4/migrating-from-v3/_index.en.md
content/community/changelog/app-nuget/v8/migrating-from-v7/_index.en.md

Add cli upgrade instructions

---

content/community/roadmap/productfeatures.drawio.svg

More updates

---

content/app/development/ux/logo/_index.en.md
content/app/development/ux/logo/_index.nb.md

Added code example (in a 'content-version-container') in `\content\app\development\ux\logo`
- #1433

Update with example on appLogo.url in resource.[language].json

---

content/app/guides/design/prototype/_index.en.md
content/app/guides/design/prototype/_index.nb.md

Update Prototype gif, and description. Also updated the link to the Altinn Studio Komponenter 

Olavs branch

---

content/app/development/ux/components/listComponent/_index.en.md
content/app/development/ux/components/listComponent/_index.nb.md

Fixing List component example code

---

content/security/cloud/_index.nb.md

Oppdatert kapittel om schrems II

---

content/app/development/configuration/email/_index.en.md
content/app/development/configuration/email/_index.nb.md

Add docs for IEmailNotificationClient
https://github.com/Altinn/app-lib-dotnet/issues/494

Feat 494 email

---

content/authorization/migration/_index.md

Rettet skrivefeil i overskrift

---

content/security/dpia/_index.en.md
content/security/dpia/about-security-in-altinn/_index.en.md
content/security/dpia/about-use-of-cloud/_index.en.md
content/security/dpia/change-log/_index.en.md
content/security/dpia/conclusion/_index.en.md
content/security/dpia/introduction/_index.en.md
content/security/dpia/privacy-assessments/_index.en.md
content/security/dpia/processing-and-purpose/_index.en.md
content/security/dpia/summary/_index.en.md

Altinn 3 DPIA now translated to english

DPIA v2.6 - English translation

---

content/app/app-dev-course-v2/modul2/index.en.md
content/app/app-dev-course/modul3/_index.en.md
content/app/guides/access-management/studio/_index.en.md
content/app/guides/access-management/studio/_index.nb.md

Translation and cleanup of https://docs.altinn.studio/app/guides/access-management/studio/

Studio access management cleanup and translation

---

content/app/development/ux/components/customButton/_index.en.md
content/app/development/ux/components/customButton/_index.nb.md

Documentation outlining the process of adding serverAction to desired process steps. The documentation is provided in both Norwegian and English

Add Documentation for Adding serverAction to Process Steps

---

content/api/broker/_index.en.md
content/api/broker/_index.nb.md
content/api/broker/spec/_index.en.md
content/api/broker/spec/_index.nb.md
content/broker/solution-architecture/_index.en.md
static/swagger/altinn-broker-v1.json

The docs should contain all the Swaggers.

Added Broker API API documentation

---

content/security/dpia/about-use-of-cloud/_index.en.md
content/security/dpia/about-use-of-cloud/_index.nb.md

Added link in chapter 3.5.1 to Entra ID MFA data residency documentation

Added link to Entra ID MFA data residency doc

---

content/app/development/ux/texts/_index.en.md
content/app/development/ux/texts/_index.nb.md

Added some more details on text formatting in apps.

more details on how to format texts

---

content/altinn-studio/user-guides/advanced/dynamics/_index.en.md
content/altinn-studio/user-guides/advanced/dynamics/_index.nb.md

Make dynamics user guide available.

un-hide dynamics guide

---

content/security/dpia/processing-and-purpose/_index.nb.md

Lagt til folkeregisterloven i grunnlag for hvilke folkeregisteropplysninger vi behandler

La til folkeregisterloven i grunnlag for hvilke folkeregisteropplysninger vi behandler

---

content/security/dpia/about-use-of-cloud/_index.nb.md

Oppdatert navn på vår databehandler

Oppdatert navn på databehandler

---

content/app/app-dev-course/case/_index.en.md

Changes lower case f in Innbygger.Fornavn to upper case.
This should be correct according to the XSD file:
```
<xsd:complexType name="Innflytter">
<xsd:sequence>
<xsd:element name="Fornavn" minOccurs="1" maxOccurs="1" type="xsd:string"/>
<xsd:element name="Etternavn" minOccurs="1" maxOccurs="1" type="xsd:string"/>
<xsd:element name="Mellomnavn" nillable="true" minOccurs="0" maxOccurs="1" type="xsd:string"/>
<xsd:element name="Alder" nillable="true" minOccurs="0" maxOccurs="1" type="xsd:integer"/>
<xsd:element name="Arbeidsinformasjon" minOccurs="1" maxOccurs="1" type="Arbeidsinformasjon"/>
<xsd:element name="KanBrukeSkjema" nillable="true" minOccurs="1" maxOccurs="1" type="xsd:boolean"/>
<xsd:element name="TidligereBosteder" minOccurs="1" maxOccurs="10" type="Adresse"/>
<xsd:element …
```

Studio intro course: Big F in Fornavn

---

content/authorization/modules/accessgroups/type-accessgroups/tilgangsgrupper-innbyggere.md

- Updating the name of Skatteetaten correctly
- https://github.com/Altinn/altinn-support-private/issues/2674

fixing Skatteetaten name

---

layouts/partials/topbar.html
themes/hugo-theme-altinn/layouts/partials/search.html
themes/hugo-theme-altinn/static/js/search.js

Improvements to search:
- Set focus in search field
- Patched app-search-javascript 8.4.1 => 8.13.0
- Removed filter on language
- Upgraded Elastic Search to latest version
- Tuned relevance
- Improved result settings

Search tuning

---

content/community/contributing/handbook/docker/without-docker-desktop/macos/index.md

Added todo notice

---

CONTRIBUTING.md
README.md
content/broker/introduction/_index.nb.md
content/broker/solution-architecture/_index.en.md
content/broker/solution-architecture/_index.nb.md
static/css/vscode-altinn-preview.css

Updated the readme after https://github.com/Altinn/altinn-studio-docs/pull/1560

Added doc for github.dev in readme

---

content/security/dpia/introduction/_index.en.md

A minor change in one word

---

content/api/storage/instances/_index.en.md
static/swagger/altinn-platform-storage-v1.json

Altinn Storage GitHub issue 3 documentation update
Altinn Storage GitHub issue 3 documentation update
- https://github.com/Altinn/altinn-storage/issues/3

Altinn Storage GitHub issue 3 documentation update

---

.vscode/settings.json

Removed hardcoded vscode theme setting

---

content/community/about/_index.en.md
content/community/about/_index.nb.md

Updated the number of service owners

Updated service owners

---

content/authentication/systemauthentication/_index.md

Autzh update

---

content/api/apps/process/_index.en.md
content/api/apps/process/_index.nb.md
content/app/app-dev-course/modul5/_index.en.md
content/app/app-dev-course/modul5/_index.nb.md
content/app/development/configuration/process/Data_Confirmation_Process.bpmn
content/app/development/configuration/process/Data_Data_Data_Process.bpmn
content/app/development/configuration/process/Data_Process.bpmn
content/app/development/configuration/process/exclusive-gateways/_index.en.md
content/app/development/configuration/process/exclusive-gateways/_index.nb.md
content/app/development/logic/dataprocessing/_index.en.md
content/app/development/logic/dataprocessing/_index.nb.md
content/app/development/process/flowcontrol/_index.en.md
content/app/development/process/flowcontrol/_index.nb.md
content/app/development/ux/components/Checkboxes/_index.nb.md
content/community/changelog/app-nuget/v8/_index.en.md
content/community/changelog/app-nuget/v8/_index.nb.md

Updates various documentation to v8

---

content/authorization/architecture/resourceregistry/actionoptions.json

Actoin update

---

content/app/development/logic/expressions/_index.en.md
content/app/development/logic/expressions/_index.nb.md

RemoveHiddenDataPreview is called RemoveHiddenData in v8, added version selector for this

Add version selector to removehiddendata

---

content/altinn-studio/guides/design/guidelines/components/file-upload/_index.nb.md
content/app/guides/design/guidelines/components/file-upload/_index.nb.md
content/broker/getting-started/developer-guides/events/_index.nb.md
content/community/devops/teams/authorization/designfrontendprocess/_index.en.md
content/community/devops/teams/authorization/designfrontendprocess/_index.nb.md

Inspired by @engeir (#1725), I did a search for other places where we had used the term "i forhold til" incorrectly. This PR rectifies those occurrences of bad language use.

Minor: Correct wrong use of "i forhold til"

---

content/correspondence/getting-started/developer-guides/events/_index.en.md
content/correspondence/getting-started/developer-guides/events/_index.nb.md

Ryddet opp litt på den norske siden for events, som hadde noen referanser til formidling. 
Lagt til alle events for avsendere og mottakere

add specific events

---

content/authorization/what-do-you-get/functionalareas.drawio.svg

updates model

---

i18n/en.yaml
i18n/nb.yaml
layouts/partials/product-switcher.html
themes/hugo-theme-altinn/layouts/partials/language-switcher.html

- Added Dialogporten and Notifications to product switcher
- Added proper i18n to the switcher
- Fixed deprecated .Site.IsMultiLingual

Added missing products

---

content/altinn-studio/concepts/signing/_index.en.md
content/altinn-studio/concepts/signing/_index.nb.md

This change adds a concept page describing signing in Altinn 3 applications.

Add page describing signing as a concept.

---

content/altinn-studio/concepts/_index.en.md
content/altinn-studio/concepts/_index.nb.md

Add children to concepts

---

content/altinn-studio/reference/logic/dynamic/_index.en.md
content/altinn-studio/reference/logic/dynamic/_index.nb.md

We have removed the RuleHandler.js file from the app template. 
Updated the documentation to inform users what to do if they need this file.

updated docs on rulehandler file

---

static/swagger/altinn-correspondence-v1.json

Changes done:
- Remove migration controller endpoints
- Add `Published` field
- Fix: use correct and updated `InitializeCorrespondenceResponseExt`

Change init correspondence response object

---

static/swagger/altinn-correspondence-v1.json

Updated swagger for correspondence:
- Most of the members have just been rearranged
- Some member were incorrect with lowercase instead of uppercase

update correspondence swagger

---

content/altinn-studio/getting-started/app-dev-course/modul6/industri.json

Got feedback from someone that had trouble finishing the code list module in the Studio tutorial. The reason was that the Studio backend currently does not support uploading code lists with values other than strings. This fixes the tutorial while we work on the problem in Studio.

Update code list with string vales

---

content/altinn-studio/guides/development/prefill/config/_index.nb.md

Entering the data model name in the field does not work.

Remove misleading datamodel object

---

content/altinn-studio/getting-started/app-dev-course/modul6/industri.json
content/authentication/what-do-you-get/systemuser/_index.md
content/authentication/what-do-you-get/systemuser/_index.nb.md
content/authorization/what-do-you-get/resourceregistry/svvdinsidesample.json

svv sample

---

content/api/accessmanagement/appsOpenAPI/_index.en.md
content/api/accessmanagement/appsOpenAPI/_index.nb.md
static/swagger/altinn-platform-accessmanagement-v1-apps.json

Ref. Issue: https://github.com/Altinn/altinn-access-management/issues/825
- Added OpenApi specification for API for Altinn Apps to perform delegation of instance access

AccessMgmt OpenApi Spec for Apps

---

static/swagger/altinn-platform-accessmanagement-v1-apps.json

Ref. Issue:
https://github.com/Altinn/altinn-access-management/issues/825

AccessMgmt AppInstanceDelegation OpenApi tweaks

---

content/altinn-studio/guides/administration/access-management/studio/_index.en.md
content/altinn-studio/guides/administration/access-management/studio/_index.nb.md

with details on how to remove a user.

updated access management guide for studio

---

static/swagger/altinn-correspondence-v1.json

Updates in the swagger docs to reflect the changes done in the API:
https://github.com/Altinn/altinn-correspondence/pull/459
https://github.com/Altinn/altinn-correspondence/pull/466

update swagger for initialize and remove ignore for api endpoints

---

content/broker/broker-transition/about/_index.en.md
content/broker/broker-transition/about/_index.nb.md
content/broker/broker-transition/getting-started/_index.en.md
content/broker/broker-transition/getting-started/_index.nb.md
content/broker/broker-transition/technical-overview/_index.en.md
content/broker/broker-transition/technical-overview/_index.nb.md
content/broker/getting-started/service-owner/_index.en.md
content/broker/getting-started/service-owner/_index.nb.md
static/swagger/altinn-broker-v1.json

Updated Doctumentation of Broker Transition solution to reflect changes in Manifest.xml: - it is now supported.
Added Resource and ServiceOwner to API Spec.
Related Issue(s)
https://github.com/Altinn/altinn-broker/issues/587
https://github.com/Altinn/altinn-broker/issues/573
https://github.com/Altinn/altinn-broker/issues/550

Broker Transition Manifest.xml

---

content/broker/getting-started/developer-guides/_index.en.md
content/broker/getting-started/developer-guides/_index.nb.md
content/broker/getting-started/developer-guides/service-owner/_index.en.md
content/broker/getting-started/developer-guides/service-owner/_index.nb.md

Corrected some broken links in Broker pages that went against the Broker Repo.

Corrected some broken links in Broker pages.

---

content/broker/getting-started/developer-guides/receive-files/_index.en.md
content/broker/getting-started/developer-guides/receive-files/_index.nb.md
content/broker/getting-started/developer-guides/send-files/_index.en.md
content/broker/getting-started/developer-guides/send-files/_index.nb.md
content/broker/getting-started/service-owner/_index.en.md
content/broker/getting-started/service-owner/_index.nb.md

Corrected all broken links to Broker Postman collection

Corrected all broken links to Broker Postman collection

---

content/broker/explanation/advanced-use-cases/very-large-files/_index.en.md
content/broker/explanation/advanced-use-cases/very-large-files/_index.nb.md
content/dialogporten/reference/graphql/_index.md
static/swagger/altinn-broker-v1.json

Documentation of large files in Broker

Documentation of large files in Broker + fix Hugo build

---

content/broker/broker-transition/getting-started/_index.en.md

Default values given in documentation leads to error.

Fix broker solution grace period documentation

---

static/swagger/altinn-correspondence-v1.json

Update swagger to reflect changes made in https://github.com/Altinn/altinn-correspondence/pull/511

update swagger doc

---

content/altinn-studio/guides/design/guidelines/components/title-and-paragraph/_index.en.md
content/altinn-studio/guides/design/guidelines/components/title-and-paragraph/_index.nb.md

Endret link til eksempler i Figma

Figma linker

---

content/correspondence/reference/API endpoints/download attachment/_index.en.md
content/correspondence/reference/API endpoints/download attachment/_index.nb.md

New documentation for the download attachment endpoint in correspondence

Added doc for download attachment

---

content/correspondence/reference/API endpoints/purge/_index.en.md
content/correspondence/reference/API endpoints/purge/_index.nb.md

Added documentation for the purge endpoint in Correspondence.

Added doc for purge endpoint

---

content/altinn-studio/designer/build-app/ui-designer/components/index.en.md
content/altinn-studio/guides/design/guidelines/components/button/_index.en.md
content/altinn-studio/guides/design/guidelines/components/button/_index.nb.md
content/altinn-studio/guides/design/guidelines/components/checkbox/_index.en.md
content/altinn-studio/guides/design/guidelines/components/checkbox/_index.nb.md
content/altinn-studio/guides/design/guidelines/components/date/_index.en.md
content/altinn-studio/guides/design/guidelines/components/date/_index.nb.md
content/altinn-studio/guides/design/guidelines/components/dropdown/_index.en.md
content/altinn-studio/guides/design/guidelines/components/dropdown/_index.nb.md
content/altinn-studio/guides/design/guidelines/components/error-message/_index.en.md
content/altinn-studio/guides/design/guidelines/components/error-message/_index.nb.md
content/altinn-studio/guides/design/guidelines/components/file-upload/_index.en.md
content/altinn-studio/guides/design/guidelines/components/file-upload/_index.nb.md
content/altinn-studio/guides/design/guidelines/components/helptext/_index.en.md
content/altinn-studio/guides/design/guidelines/components/helptext/_index.nb.md
content/altinn-studio/guides/design/guidelines/components/input/_index.en.md
content/altinn-studio/guides/design/guidelines/components/input/_index.nb.md
content/altinn-studio/guides/design/guidelines/components/picture-component/_index.en.md
content/altinn-studio/guides/design/guidelines/components/picture-component/_index.nb.md
content/altinn-studio/guides/design/guidelines/components/radiobutton/_index.en.md
content/altinn-studio/guides/design/guidelines/components/radiobutton/_index.nb.md
content/altinn-studio/guides/design/guidelines/components/select/_index.en.md
content/altinn-studio/guides/design/guidelines/components/select/_index.nb.md
content/altinn-studio/guides/design/guidelines/components/title-and-paragraph/_index.en.md
content/altinn-studio/guides/design/guidelines/components/title-and-paragraph/_index.nb.md

Har oppdatert linker for ui komponenter

Har oppdatert figma linker

---

content/authentication/what-do-you-get/_index.nb.md

- Correcting some grammar mistakes
- Changing "JWT token" -> "JWT", as the T already stands for _token_

Authentication - "Hva får du?" - Minor grammar improvements

---

content/authorization/getting-started/resource-admin-studio/_index.nb.md

- In norwegian docs, the resources repo name should be `{org}-resources`, not `{org}-ressurser`

Fix repo name of resource repo

---

content/authorization/architecture/resourceregistry/accesspackages_hier.json

- Remove "Opptre for virksomhetens kunder" from access packages list
- Fix duplicate urns for access packages

Update accesspackages after discussions

---

content/broker/broker-transition/getting-started/_index.en.md
content/broker/broker-transition/getting-started/_index.nb.md

Updated broker transition doc with additional details about SRR Caching, as well as corrected som mispellings/discrepancies between language versions.
Related issue: https://github.com/Altinn/altinn-broker/issues/630

Updated broker transition doc with additional details

---

content/correspondence/getting-started/developer-guides/events/_index.en.md
content/correspondence/getting-started/developer-guides/events/_index.nb.md
content/correspondence/getting-started/developer-guides/notifications/_index.en.md
content/correspondence/getting-started/developer-guides/notifications/_index.nb.md

Fikser link titler som var feil på utviklerguides

fix link titles

---

content/correspondence/transition/differences/_index.nb.md

Feil i dokumentasjonen. Vi godtar ikke HTML

fix error in documentation

---

content/correspondence/getting-started/developer-guides/notifications/_index.en.md
content/correspondence/getting-started/developer-guides/notifications/_index.nb.md

Norwegian version vil be provided after we agree on the format.

Updated docs for custom recipient

---

content/altinn-studio/reference/ux/components/Checkboxes/_index.en.md

added-anatomy-checkbox

---

static/swagger/altinn-broker-v1.json

Set the accept of downloadfile correctly so that generators behave as expected

Set the accept of downloadfile

---

content/altinn-studio/guides/development/copy-app/_index.en.md
content/altinn-studio/guides/development/copy-app/_index.nb.md

Updated docs after feedback, to ensure copy of app goes smoothly for users

add "reset repo" as a explicit step

---

content/altinn-studio/guides/development/subform/backend-manual/_index.en.md
content/altinn-studio/guides/development/subform/backend-manual/_index.nb.md

- https://github.com/Altinn/app-frontend-react/pull/3066

Removing type union for subform layout-set

---

content/altinn-studio/guides/development/undeploy/_index.en.md
content/altinn-studio/guides/development/undeploy/_index.nb.md

fix spacing for list

---

static/swagger/altinn-correspondence-v1.json

"Writeer" is very wrong. Caused by mass replace.

Fix wrong names of fields

---

content/community/about/open-source/_index.en.md
content/community/about/open-source/_index.nb.md

- Text improvements
- Updated links
- Updated software list
- Added Switzerland

Updates to OSS page

---

static/swagger/altinn-notifications-v1.json

This is a part of https://github.com/Altinn/altinn-notifications/issues/764

Update the swagger documentation.

---

content/altinn-studio/reference/ux/components/Address/_index.nb.md

Added the NO name and the description used in the Studio UI for this component.

chore:update-address-component

---

content/notifications/_index.en.md
content/notifications/_index.nb.md

Added more details on how to get SMS working in test and expected roundtrip-times for updating information involving external sources.

Added more details on how to get SMS working in test 

---

content/correspondence/what-do-you-get/_index.en.md
content/correspondence/what-do-you-get/_index.nb.md

Updated correspondence documentation by adding an explanation for transmissions

Updated correspondence documentation with transmissions

---

content/authorization/what-do-you-get/accessgroups/accessgroups/forholdVedVirksomheten/_index.en.md
content/authorization/what-do-you-get/accessgroups/accessgroups/forholdVedVirksomheten/_index.nb.md
content/authorization/what-do-you-get/accessgroups/accessgroups/personale/_index.en.md
content/authorization/what-do-you-get/accessgroups/accessgroups/personale/_index.nb.md

Lagt til ny pakke Lønn med personopplysninger av særlig kategori

Ny tilgangspakke NAV
