- content/known-issues/breaking-changes/_index.md
Right now the page has two H1 headers. Only one is needed.
> Fix for double header in breaking changes page

- content/teknologi/altinnstudio/altinn-api/clients/_index.md
- static/swagger/altinn-platform-storage-v1.json
A small fix removing mention about Application.PresentationField and Instance.PresentationField as they have been removed.
Related to issue 4135 for altinn-studio repo.
> Remove PresentationField from docs

- config.toml
To be able to handle different presentations of list, tables, etc. in markdown using CSS, I've enabled [attribute lists](https://gohugo.io/getting-started/configuration-markup/#goldmark) in Goldmark, the markdown parser used by Hugo.
This markdown list...
```markdown
- list item 1
- list item 2
{.connected-bullets}
```
...will be renedered as this html
```html
<ul class="connected-bullets">
<li>list item 1</li>
<li>list item 2</li>
</ul>
> Enable attribute lists in Hugo

- .vscode/settings.json
Added the following default settings for editing markdown in vscode.
- `"editor.wordWrap": "off"` - **Don't wrap lines of text automatically** since that hides long lines. Long lines are hard to read, causes horizontal scrolling and makes diffing changes harder in git, and should thus be avoided. Markdown should be readable as markdown.
- `"editor.renderWhitespace": "trailing"` - In markdown, two trailing spaces at the end of a line will render as newline when converted to HTML. **Now trailing spaces are visible in vscode.**
- `"files.trimTrailingWhitespace": false` - **Avoid automatically trimming trailing spaces** when saving, ref. the issue above.
- `"editor.rulers": [ 120 ]` - A ruler to help remembering adding too long lines, 120 seems like an ok value for this.
> Added better defaults for markdown in vscode

- content/app/development/ux/images/_index.en.md
- content/app/development/ux/images/_index.nb.md
Docs changes related to https://github.com/Altinn/altinn-studio/pull/7484
* Suggest using `wwwroot` in image url
* use `applicationId` instead of instructing users to manually replace
text in the instructions
* Suggest that UseStaticFiles might be pressent in newer apps.
> Improve image component docs

- content/technology/solutions/altinn-studio/designer/functional/build-app/ui-designer/components/index.md
It took me a while to figure out the names, and the docs were not helpful when I was writing JSON.
> Studio and json used different terminology for the Header/Title component

- content/app/development/logic/validation/_index.en.md
- content/app/development/logic/validation/_index.nb.md
added example to clarify that error message should be added to property and not definition
> clearified docs on custom json schema message

- content/app/development/configuration/secrets/_index.en.md
- content/app/development/configuration/secrets/_index.nb.md
- content/app/development/configuration/settings/_index.en.md
- content/app/development/configuration/settings/_index.nb.md
- A dead link revived
- Removed NuGet package version requirements under the assumption that all apps now have 1.2.2 or newer already.
> Fix secret link from settings

- content/app/launched-apps/_index.en.md
The "Info" link of STAMIs two first services pointed at the temporary project page directly. They have been modified to point at a url-shortener, that will persist.
> Correct direct links to permanent links

- content/api/authentication/enterpriseuser/_index.en.md
- content/api/authentication/enterpriseuser/_index.nb.md
- content/community/devops/roadmapprocess/_index.en.md
I found some broken delimiters that prevented `hugo` from compiling the docs successfully
> Fixing broken delimiters

- content/community/changelog/storage-interfaces/v3/_index.en.md
- content/community/changelog/storage-interfaces/v3/_index.nb.md
Adds release notes for 3.1.0 of storage interface introducing a new property for controlling anonymous access on stateless apps.
> docs: add release notes for 3.10.0 of storage interface

- content/community/changelog/app-frontend/v3/whats-new/_index.en.md
- content/community/changelog/app-frontend/v3/whats-new/_index.nb.md
Since we are now using Github Releases, and automatically generate the changelog on release, we no longer have to maintain this list manually.
> chore: add link to github releases and roadmap for app-frontend

- content/app/app-dev-course/modul2/_index.en.md
- content/app/app-dev-course/modul4/_index.en.md
- content/app/app-dev-course/modul5/_index.en.md
Missing translation for link titles in app dev course
> fixed translation of link titles

- themes/hugo-theme-altinn/layouts/_default/li.html
- themes/hugo-theme-altinn/layouts/_default/list.html
- themes/hugo-theme-altinn/layouts/partials/footer.html
- themes/hugo-theme-altinn/layouts/partials/header.html
- themes/hugo-theme-altinn/layouts/partials/menu.html
- themes/hugo-theme-altinn/layouts/shortcodes/children.html
Done the following tweaks:
- Cache the left menu so it's generated only once. Use js to set active class instead of hugo.
- Commented out not used feature for back/forward navigation in footer
- Removed word count check for toc
- Cleanup
> Improve build performance

- content/community/changelog/app-nuget/v6/breaking-changes/_index.en.md
- content/community/changelog/app-nuget/v6/breaking-changes/_index.nb.md
To avoid issues when Program.cs changes in V7.
https://github.com/Altinn/app-template-dotnet/issues/125
> doc: Update V6 upgrade doc to point to specific commit id instead of latest version of Program.cs

- content/community/changelog/app-nuget/v6/whats-new/_index.en.md
- content/community/changelog/app-nuget/v6/whats-new/_index.nb.md
add release notes for v6.0.2 of nugets
> add release notes for v6.0.2 of nugets

- content/app/development/data/options/_index.en.md
- content/app/development/data/options/_index.nb.md
- content/community/changelog/app-frontend/v3/whats-new/_index.en.md
- content/community/changelog/app-frontend/v3/whats-new/_index.nb.md
Changed title for options based on repeating groups in the data model to be more understandable for the app developers and not expose implementation details that strictly do not matter.
Also some fixing of linting rules.
> docs: change title for options based on the datamodel

- content/app/development/configuration/stateless/_index.en.md
- content/app/development/configuration/stateless/_index.nb.md
The lower and upper-case naming of `Stateless` and `stateless` for the layout set and data model caused confusion when talking about how to configure a stateless app.
Now has a more explicit naming for the data model to make this easier to follow where the layout-set is named `stateless` and the model is called `Stateless-model`
> docs: differentiate between layout set and model

- content/app/development/logic/expressions/_index.en.md
- content/app/development/logic/expressions/_index.nb.md
Update expressions docs with an example of controlling edit button text in repeating groups using expressions for textResourceBindings.
> expressions doc changes and new example

- content/app/development/data/options/_index.en.md
- content/app/development/data/options/_index.nb.md
- content/community/changelog/app-frontend/v3/whats-new/_index.en.md
- content/community/changelog/app-frontend/v3/whats-new/_index.nb.md
Our documentation describes building options dynamically from the data model, but referred to redux (the react state library used _to store the data model_). This is a very technical (and irrelevant) detail in the documentation.
- https://github.com/Altinn/app-frontend-react/issues/530
> Removing references to redux

- content/app/development/configuration/eformidling/_index.en.md
EFormidling monitor page link without tt02 is not functional, this proposed change assumes previous link was not used for monitoring shipments in prod. environment.
https://docs.altinn.studio/app/development/configuration/eformidling/
changes to link given in documentation:
`https://platform.altinn.no/eformidling/api/conversations?messageId={instanceGuid}` => `https://platform.tt02.altinn.no/eformidling/api/conversations?messageId={instanceGuid}`
Docs
> change to eformidling monitoring link

- content/app/app-dev-course/modul5/_index.en.md
- content/app/app-dev-course/modul5/_index.nb.md
- content/app/development/configuration/process/Data_Confirmation_Process.bpmn
- content/app/development/configuration/process/Data_Data_Data_Process.bpmn
- content/app/development/configuration/process/Data_Process.bpmn
- content/app/development/configuration/process/_index.en.md
- content/app/development/configuration/process/_index.nb.md
- content/technology/architecture/capabilities/runtime/processing/process/_index.md
The process example files was a bit mal placed in the `altinn-studio` after we deceided to split the repo. These files is just used in this documentation, so we rather just place them here.
> moving process templates to the docs repo

- content/app/development/configuration/eformidling/_index.nb.md
Link changed to include tt02, explanation slightly more specific. 
Since appdevs don't have access to the equivalent for prod is not included
> Correcting link for eformidling shipment monitor

- content/app/development/ux/pages/summary/_index.en.md
- content/app/development/ux/pages/summary/_index.nb.md
These summaries are also no longer just for repeating groups, but also works for non-repeating groups.
> Adding docs for `excludedChildren` in summary

- content/app/development/ux/pages/tracks/_index.en.md
- content/app/development/ux/pages/tracks/_index.nb.md
Startup.cs was removed from v6. 
AddTransient<IPageOrder, CustomOrder>(); is correct since the class in step 1 is CustomOrder : IPageOrder
> Update Tracks doc for v6 and 7.

- content/app/app-dev-course/case/_index.en.md
- content/app/app-dev-course/modul1/_index.en.md
- content/app/app-dev-course/modul2/_index.en.md
- content/app/app-dev-course/modul3/_index.en.md
- content/app/app-dev-course/modul4/_index.en.md
- content/app/app-dev-course/modul5/_index.en.md
- content/app/app-dev-course/modul6/_index.en.md
The improvements include:
- use more common synonyms for certain words
- remove irrelevant information in instructions
- use national id number instead of Social Security number (which is only used in the U.S)
> Fixed spelling and improved grammar of English dev course docs.

- content/app/development/ux/fields/grouping/alternatives/_index.en.md
- content/app/development/ux/fields/grouping/alternatives/_index.nb.md
Updated settings docs in Grouping to include recent added property option "alwaysShowAddButton"
- https://github.com/Altinn/app-frontend-react/pull/1071
> added alwaysShowAddButton property

- content/api/models/app-metadata/_index.en.md
- content/api/models/app-metadata/_index.nb.md
- content/app/development/configuration/messagebox/create_copy/_index.en.md
- content/app/development/configuration/messagebox/create_copy/_index.nb.md
Documentation for the **Create new copy** functionality.
- https://github.com/Altinn/altinn-platform/issues/355
> Add documentation for create new copy

- content/app/development/ux/components/grid/_index.en.md
- content/app/development/ux/components/grid/_index.nb.md
Rewriting the grid text width/alignment/overflow options docs, as it referred to an object that is only used in repeating groups (not in the Grid component). Adding an example for clarity.
> Grid cell option updates

- content/app/getting-started/create-app/_index.en.md
- content/app/getting-started/create-app/_index.nb.md
On first login I'm taken to altinn.studio/repos. I added a note to click on the logo if not taken directly to Studio dashboard (altinn.studio/dashboard) when logging in and added link to studio dashboard. Also fixed a few typos.
> Click logo to navigate to Studio dashboard

- content/events/publish-events/get-started/api-access/_index.en.md
- content/events/subscribe-to-events/get-started/api-access/_index.en.md
- themes/hugo-theme-altinn/layouts/shortcodes/insert.html
Added if check to the insert-shortcode. 
Build does not break if file does not exists or cannot be found. 
Error message is simply printed to the page where content should have been inserted.
> more robust insert shortcode

- themes/hugo-theme-altinn/layouts/shortcodes/expandbold.html
Created a version of the `expand` shortcode with a slightly larger arrow and bold header.
> Added hugo config version to expand shortcode so it works with '%'

- themes/hugo-theme-altinn/layouts/shortcodes/expand.html
- themes/hugo-theme-altinn/layouts/shortcodes/expandbold.html
- themes/hugo-theme-altinn/layouts/shortcodes/expandlarge.html
Added dashes inside curly braces in expandlarge, expand, and expandbold shortcodes.
This makes it possible to use nested expand shortcodes.
> Update Hugo expand shortcodes

- content/app/development/ux/components/alertComponent/_index.en.md
- content/app/development/ux/components/alertComponent/_index.nb.md
Updates the docs with the use of `body` instead of `description` for `textResourceBindings` for `Alert`.
> fix(Alert): update docs to reflect using body as textResourceBindings instead of description

- content/app/development/data/options/_index.en.md
- content/app/development/data/options/_index.nb.md
- https://github.com/Altinn/app-frontend-react/pull/1370
> Added docs for static query parameters in options

- content/app/development/ux/components/accordion/_index.en.md
- content/app/development/ux/components/accordion/_index.nb.md
Documents the property `headingLevel` for the `Accordion` component.
> fix(Accordion): Document headingLevel option

- content/app/app-dev-course/modul1/_index.nb.md
Fjernet dobbel "beskriver hva som"
> Fix typo in _index.nb.md

- layouts/shortcodes/code-title.html
- static/css/custom.css
- Shortcode code-title that adds code formatting with class .code-title to content
- Styling of .code-title
The shortcode is added just before a code block. The result is a slightly lighter field at the top of the block where the title within the shortcode (e.g. file name) is displayed.
> Shortcode and styling for code block title

- static/css/custom.css
- themes/hugo-theme-altinn/layouts/shortcodes/expandsmall.html
- Markdownify header in expandsmall shortcode
- Add CSS styling to format code in expandsmall header
> Fix styling of expandsmall shortcode to allow formatting of header

- CONTRIBUTING.md
- content/community/changelog/app-frontend/stricter-schema/_index.en.md
We were reminded about `CONTRIBUTING.md` today, [and I commented](https://altinndevops.slack.com/archives/C045EB3JA9X/p1695027440677159) about my difference in opinion about framing ones own opinion as questions to the author. I prefer the direct, but polite (possibly more Scandinavian?) approach of just putting your opinion out there.
This might be controversial, but I dislike rhetorical questions in code review, and I believe reviewers should strive to only ask questions to the author when they _do not know the answer themselves_. At the more extreme end of the asking-questions-in-code-reviews spectrum lies a manipulation tactic where the author might be made to feel stupid ("why didn't you think of doing _x_?").
Also, sneaking in an entirely unrelated change where I forgot a "we" 😇
- …
> Changes to CONTRIBUTING.md

- content/app/development/ux/organisation-logo/_index.en.md
- content/app/development/ux/organisation-logo/_index.nb.md
Documents the use of the `size` parameter in settings for organisation logo.
> chore: update organisation logo documentation with size parameter

- content/app/development/logic/events/subscribing/_index.en.md
- content/app/development/logic/events/subscribing/_index.nb.md
The documentation did not state that this doesn't work in localtest environment. Fixed this as well as adding a line on how to configure dotnet user-secrets locally.
- N/A
> Added text to clarify missing localtest support and how to configure with user-secrets

- content/app/development/logic/validation/_index.en.md
Removes a |-character that was accidentally added in #1378
> fix: remove accidental |-character in soft validation documentation

- content/notifications/send-notifications/get-started/user-guide/_index.en.md
This is the documentation for SMS mobile number specification.
Here mobile number specification added to the user guide.
- https://github.com/Altinn/altinn-notifications/issues/328
> Altinn Notification SMS mobile number specification

- content/community/contributing/handbook/back-end/nuget-package/_index.md
This PR is the result of this PR discussion: https://github.com/Altinn/altinn-platform/pull/670#discussion_r1484201664
> `dotnet` version bumped from 7 to 8 for NuGet automation

- content/app/development/configuration/process/customize/_index.en.md
- content/app/development/configuration/process/customize/_index.nb.md
- content/community/changelog/app-frontend/v4/_index.en.md
This PR adds documentation of how to use the new layout-set based way of configuring custom receipt pages. 
- Altinn/app-frontend-react#1468
> fix: add documentation for the new layout-set based receipt

- .github/workflows/hugo.yml
Bump Hugo to v0.124.0
https://github.com/gohugoio/hugo/releases/tag/v0.124.0
> Bump Hugo to v0.124.0

- content/app/app-dev-course/modul3/_index.en.md
- content/app/app-dev-course/modul3/_index.nb.md
There are a couple of issues with the documentation around test users/logins for the dev course
* TestID is what I used during the course, so I figure that should be mentioned as an option? It seems to work for the test case of the course
* The link for testing dataset was dead, I'm guessing the correct link should be this: https://pedia.altinn.cloud/altinn-3/testing/test-data/
N/A
> Improve information around available test-user login methods for the dev course

- content/app/app-dev-course/modul3/_index.en.md
- content/app/app-dev-course/modul3/_index.nb.md
When I worked my way through the dev course, I had initially created a personal application (not tied to an org),
@tjololo told me I could move the app to the test-org with access to tt02 by moving the repository and updating the application metadata.
This PRs adds to the module 3 warning notice, giving users the option to proceed with the module by moving the personal application into an org.
N/A
> Guidance on moving/migrating a personal application to an organization for module 3 of the dev course

- content/api/guides/appownerintegration/receivingdata/_index.md
Some updated links
Another user found some missing, broken and wrong links in this documentation. Found some of the correct links (i think.. please double check). Might add more later when i've found them.
Other missing links include:
- https://docs.altinn.studio/api/guides/appownerintegration/receivingdata/#overordnet-prosess-sluttbruker - Wrong link on number 5
- https://docs.altinn.studio/api/guides/appownerintegration/receivingdata/#instansiering-av-tjeneste - Missing link on how TE can instantiate an app possible links: (https://docs.altinn.studio/nb/api/apps/instances/#create-instance) || (https://docs.altinn.studio/nb/app/development/logic/instantiation/#eksempel-2---instansiering-kun-tillatt-for-applikasjonseier)
> Broken links

- content/authorization/migration/servicemigrationplan/_index.md
Rettet en del datoer. Hentet datoer fra Github Roadmap. Noe mangler, men det er vesentlig bedre
> Updated dates for authorization migration plan

- content/app/getting-started/create-app/settings/_index.en.md
- content/app/getting-started/create-app/settings/_index.nb.md
A couple links containing "/en/" were not working.
> docs: fix broken links

- content/community/changelog/app-frontend/v4/_index.en.md
- content/community/changelog/app-frontend/v4/migrating-from-v3/_index.en.md
This PR documents how a service owner can opt-in to get automatic tracks migration pull requests generated for their repositories.
> add documentation of how to opt-in for automatic tracks migration

- static/swagger/altinn-platform-accessmanagement-v1-resourceowner.json
Fixed error in generated json example
> Fix access-management resource owner swagger example

- content/app/development/logic/expressions/_index.en.md
Some properties in the table of the English documentation had the Norwegian name "streng" for "string".
This is now fixed.
> Update norw "streng" to eng "string"

- .vscode/extensions.json
- .vscode/settings.json
- config.toml
- static/css/vscode-altinn-preview.css
This PR creates a new flow for simple changes in the documentation using [vscode running in your browser](https://docs.github.com/en/codespaces/the-githubdev-web-based-editor).
Currently "non-devs" have a hard time, and instead of running docs locally they just edit files on github.com without preview, one file per PR. This PR fixes that for simple changes:
- **No need to install or run git, hugo or vscode locally**
- Just open github.dev from docs.altinn.studio link (at the bottom of each page) 
- Preview instantly available, press ![image](https://github.com/Altinn/altinn-studio-docs/assets/6088624/b35b47d5-852f-4252-ac05-76a873f0a6d9)-icon or `Ctrl + Shift + V`
- Updates in real time (no need to save to see preview change)
- Also available when doing review of PR, just press `.` from …
> Preview in github.dev / vscode

- content/authorization/modules/pdp/_index.md
- content/broker/user-guides/get-started/common-steps/_index.en.md
- content/broker/user-guides/get-started/common-steps/_index.nb.md
altinn:authorization:pdp was removed so we rewrote to use our own Maskinporten client with altinn:authorization/authorize.admin instead.
> Removed altinn:authorization:pdp from docs as no longer used

- static/swagger/altinn-platform-accessmanagement-v1-resourceowner.json
Updated old scopes in swagger doc
from
```
altinn:resourceowner/authorizedparties
altinn:resourceowner/authorizedparties.admin
```
to 
```
altinn:accessmanagement/authorizedparties.resourceowner
altinn:accessmanagement/authorizedparties.admin
```
> Updated resourceowner AuthorizedParties swagger with new scope requirement

- content/app/deployment/_index.en.md
- content/app/deployment/_index.nb.md
See title. Based on feedback, updated deployment (to prod) docs to include link to information on how to get access to deploy to different environments.
> added link to how to administrate deployment access

- layouts/partials/product-switcher.html
- layouts/partials/topbar.html
- static/css/custom.css
Added a product dropdown to the topbar, which contains links to the product pages. Currently contains the following products:
- Studio
- Authorization
- Broker
- Correspondence
Also added back the community link to the topbar, as there is now space for it.
https://github.com/Altinn/altinn-studio-docs/assets/1636323/a967f625-3ea6-4145-b54f-7445ab4e495c
> topbar with product dropdown

- content/altinn-studio/guides/maskinporten-app-integration/_index.en.md
- content/altinn-studio/guides/maskinporten-app-integration/_index.nb.md
A user on Slack noted that the documentation makes use of a deprecated package for hooking up Azure KV as a configuration provider. We can't cleanup package dependencies right now (see https://github.com/Altinn/app-lib-dotnet/issues/647), but we can update the documentation so that users start using the new SDKs from Azure/MS. I avoided the `KeyVaultSettings` as it comes from a transitive depedency.
An alternative would be to enable the Azure KV configuration provider from Altinn.App.Api instead (`ConfigureAppWebHost`)
> Update Azure Key Vault config provider code to use newer packages

- config.toml
- static/js/custom.js
- themes/hugo-theme-altinn/layouts/partials/footer.html
- themes/hugo-theme-altinn/layouts/partials/header.html
- Automatic ToC to the right, showing all heading levels and page structure
- ToC highlights when scrolling page
- Changed hash-links to `gitHub-ascii` (to make this work with Norwegian)
- Always there, always clickable
> Better ToC

- content/app/guides/payment/backend-configuration/_index.en.md
- content/app/guides/payment/backend-configuration/_index.nb.md
We were using the wrong data type for the payment receipt PDF.
See https://github.com/Altinn/app-lib-dotnet/pull/697
> Add docs for how to configure payment receipt pdf data type.

- content/altinn-studio/guides/payment/backend-configuration/_index.en.md
- content/altinn-studio/guides/payment/backend-configuration/_index.nb.md
- content/altinn-studio/reference/configuration/secrets/_index.en.md
- content/altinn-studio/reference/configuration/secrets/_index.nb.md
- content/app/guides/payment/backend-configuration/_index.en.md
- content/app/guides/payment/backend-configuration/_index.nb.md
Update secret related documentation on how to use Azure Key Vault as a configuration provider. Also includes some adjustments to payment docs.
Strongly related to https://github.com/Altinn/app-lib-dotnet/pull/704
> Update secret related documentation on how to use Azure Key Vault

- layouts/partials/product-switcher.html
When products have different names in different languages, the product toggle should reflect this.
> Add language support to product toggle

- content/events/subscribe-to-events/_index.en.md
Include subnet mask to documentation of the IP address we have when pushing events.
> Add subnet mask to Events IP

- content/altinn-studio/getting-started/app-dev-course/modul1/_index.en.md
- content/altinn-studio/getting-started/app-dev-course/modul2/_index.en.md
- content/altinn-studio/getting-started/app-dev-course/modul3/_index.en.md
- content/altinn-studio/getting-started/app-dev-course/modul4/_index.en.md
- content/altinn-studio/getting-started/app-dev-course/modul5/_index.en.md
- content/altinn-studio/getting-started/app-dev-course/modul6/_index.en.md
Fixed the order of the course modules in the English Altinn Studio intro course. Also added module numbers to the title and navigation link, so that the English layout resembles the Norwegian layout.
Related to PR #1719
> English Studio course: fix order of modules and add module numbers to navigation

- .github/workflows/hugo-verifications.yml
- .github/workflows/hugo.yml
Avoid using latest since v0.134.0 released yesterday seems to have introduced a bug making link-checking fail
> Pin hugo to v0.133.1 for now

- content/api/apps/_index.en.md
- content/api/apps/_index.nb.md
- content/api/apps/data-elements/_index.en.md
- content/api/apps/data-elements/_index.nb.md
- content/api/apps/process/_index.en.md
- content/api/apps/process/_index.nb.md
- content/api/apps/validation/_index.en.md
- content/api/apps/validation/_index.nb.md
`appPath` er ikke det samme som `basePath`, men ble aldri spesifisert noe sted, så fjernet bruken, og endret de stedene den var brukt til å heller bruke `basePath`.
To steder manglet det også en `/meta` for å få hentet prosessen, så la inn det.
Til slutt prøvde jeg å være litt mer eksplisitt på at det som nevnes på førstesiden er `basePath`, i håp om å få treff der også i søkeresultater.
> Forsøk på opprydning i `appPath` vs `basePath` 

- content/broker/_index.en.md
- content/broker/_index.nb.md
- content/broker/reference/terminology/_index.en.md
- content/broker/reference/terminology/_index.nb.md
- content/correspondence/reference/capabilities/_index.nb.md
- content/correspondence/reference/solution-architecture/_index.nb.md
Broker had references to Correspondence, which should be Broker
> fix wrong naming in Broker terminology

- content/correspondence/getting-started/service-owner/_index.en.md
- content/correspondence/getting-started/service-owner/_index.nb.md
Small fixes in Getting Started Guide
Change Open->Read and Send-> Write, as well as removing See policy. 
There were some differences in the english and norwegian guide, but these match now.
> edit guide for setting up as a Service Owner

- static/swagger/altinn-correspondence-v1.json
Following PR (https://github.com/Altinn/altinn-correspondence/pull/366), a new schema has been added along with the correct response for correspondence overview. 
A double checking has also been done for the schemas to ensure it is up to date with the current api.
> fix: add published to details and overview, add notification to overview

- content/authorization/getting-started/resource-admin-studio/_index.nb.md
Team names for publishing resource should be:
- TT02: `Resources-Publish-TT02` (instead of Ressurser-Publiser-TT02)
- PROD: `Resources-Publish-PROD` (instead of Ressurser-Publiser-PROD)
> Fix team names for publishing resources

- static/swagger/altinn-platform-storage-v1.json
Copy of the OpenAPI file generated when locally running the latest version of the Storage application.
The file also includes some consequent manual edits:
- Keep `servers`
- Strip the path prefix `storage/api/v1` from the endpoints. This can be better for readability, as this part of the path is universal for all endpoints, and it already exists in the server URLs. 
- For requestBody.Content in new endpoints, the autogenerated alternatives "application/json-patch+json", "text/json", "application/*+json" have been removed. This leaves only `application/json`, which presumably is the only one which is relevant.
> Update OpenAPI spec for Storage API 

- content/correspondence/getting-started/developer-guides/notifications/_index.en.md
- content/correspondence/getting-started/developer-guides/notifications/_index.nb.md
This PR changes information for keyword support on the notification page for corrospondence. The keyword $recipientName$ is now supported for all scenarioes. Both the english and norwiegan page have been updated.
> Updated /correspondence/getting-started/developer-guides/notifications/ page

- content/authorization/guides/manage-accesslist-api/_index.nb.md
Removed '-' in from scopes in documentation which does not match the actual scopes in Samarbeidsportalen.
Also added sentence informing about access to scopes require email to servicedesk
> Fixed error in accesslist scopes

- content/altinn-studio/guides/development/copy-app/_index.en.md
- content/altinn-studio/guides/development/copy-app/_index.nb.md
Removed obsolete steps.
Updates docs for Altinn/altinn-studio#14698
> docs: remove depricated steps in copy app guide

- content/altinn-studio/guides/shared/api/base-urls.md
Correct the base URLs for the TT02 and production to use `.no` instead of `.cloud`
> Update the URL for TT02 and production

- static/swagger/altinn-notifications-v1.json
This pull request is created to revert the OpenAPI version back to 3.0.1 because the version 3.0.4 caused a rendering bug in the production
- https://github.com/Altinn/altinn-notifications/issues/786
- https://github.com/Altinn/altinn-studio-docs/pull/2103
> Use OpenAPI version 3.0.1

- content/community/changelog/deployment/migration/_index.en.md
- content/community/changelog/deployment/migration/_index.nb.md
- content/community/changelog/deployment/v3/whats-new/_index.en.md
- content/community/changelog/deployment/v3/whats-new/_index.nb.md
* Update changelog for helm deployment chart 3.2.0
> docs: update changelog deployment chart v3.2.0
